### ISSUE TITLE
Enable Dotnet client in e2e tests

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1065]
We should enable running the C# client in our e2e tests.

[Uncomment this line](https://github.com/G-Research/armada/blob/master/makefile#L333) and get these tests working.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-49) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1065?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by punithnayak** [comment]
Hey @kannon92  no one has done any progress on this issue can I take up this?

**Comment by richscott** [comment]
Closing.
