### ISSUE TITLE
www.armadaproject.io does not exist

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1081]
It's general convention (whether it should be or not) that a website works with `www` prepended. However, http://armadaproject.io works while http://www.armadaproject.io does not.

We should ensure the `www.` url is in DNS, and redirecting users to the correct, non-www URL.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-53) by [Unito](https://www.unito.io)

**Comment by pavlovic-ivan** [comment]
Hi @jayofdoom @richscott. Not sure how i can help here. Looks like you have everything configured, except a CNAME record with your domain provider. I tested your records with `dig`, the `armadaproject.io` is fine, but `www.armadaproject.io` has no records:
```
; <<>> DiG 9.10.6 <<>> www.armadaproject.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 31168
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.armadaproject.io.          IN      A

;; AUTHORITY SECTION:
armadaproject.io.       3601    IN      SOA     dns1.registrar-servers.com. hostmaster.registrar-servers.com. 1666063314 43200 3600 604800 3601

;; Query time: 72 msec
;; SERVER: 89.216.1.30#53(89.216.1.30)
;; WHEN: Fri Oct 13 09:54:36 CEST 2023
;; MSG SIZE  rcvd: 122
```
so all configuration should exist in your domain provider. Am i missing something?

**Comment by dave-gantenbein** [comment]
I'm not sure we know who the name provider is, or where to configure it. Ideally we'd just have the www. (or any subdomain) do a redirect. Can you do the detective work and help get it configured?

**Comment by pavlovic-ivan** [comment]
Let's start with who and how created and configured the domain armadaproject.io. Do you have those details?

**Comment by pavlovic-ivan** [comment]
HI all. Please check the links now, redirect should be working as expected

**Comment by dave-gantenbein** [comment]
Amazing! LGTM
