### ISSUE TITLE
build fails on linux if TESTS_IN_DOCKER isn't set

### ISSUE THREAD

**Issue by andrewpcone** [armadaproject/armada#1177]
`make proto` should work out of the box. Right now it doesn't, because `TESTS_IN_DOCKER` isn't set, which makes `GO_TEST_CMD` empty, which causes `swagger` and other commands to run on the host, rather than in docker. If the user's `PATH` doesn't include `~/go/bin` or other `$GOPATH/bin`, then `swagger` fails.

I propose that we build exclusively in docker by using `$GO_CMD` in front of all the `make proto` commands instead of relying on the system go installation.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-57) by [Unito](https://www.unito.io)

**Comment by andrewpcone** [comment]
alternatively we can have the makefile call, for example  `` `go env GOPATH`/swagger `` or similar

**Comment by kannon92** [comment]
Could someone reproduce this? Not sure if it’s fixed or not.

**Comment by Sharpz7** [comment]
Since we now use mage, this isn't needed. Closing
