### ISSUE TITLE
SPIKE: review MCAD

### ISSUE THREAD

**Issue by dave-gantenbein** [armadaproject/armada#1250]
https://github.com/IBM/multi-cluster-app-dispatcher 

Alex suspects they are no longer doing active development on this tool. Let's figure out if there are any functional gaps between it and Armada. The goal would be to approach them about collaborating and standardizing on Armada.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-62) by [Unito](https://www.unito.io)

**Comment by Sharpz7** [comment]
Closing - I think MCAD has been well evaluated at this point.
