### ISSUE TITLE
Ensure redaction in logs fetched for Lookout

### ISSUE THREAD

**Issue by dave-gantenbein** [armadaproject/armada#1256]
Use extant list for redaction.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-63) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1256?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by Sharpz7** [comment]
Closing - no longer required
