### ISSUE TITLE
Create CI/CD automation for pushing docker images

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1273]
Using documentation and scheme created in #1272, automate this process in CI, ensuring that we push built docker images when demanded by the documentation.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1273?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott
