### ISSUE TITLE
Update helm charts to use newly published GR-OSS docker images

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1274]
We should adjust the helm charts to use the new location for GR-OSS published docker images. Test the updated helm charts by using them to perform a one-time manual update of the shared test server.

Document the process so manual updates can be performed by anyone with access.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-64) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1274?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by Sharpz7** [comment]
Closing - definitely no longer relevant - a bigger ticket on Helm/Operator/Localdev/Release should be created
