### ISSUE TITLE
Automatically update EKS demo instance

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1275]
Our shared instance currently only receives manual periodic updates. Instead, we should use automation to update it on a set schedule.

Define and document an update schedule, and implement automation to perform it.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-65) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1275?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by ClifHouck** [comment]
I'll take a look at this.
