### ISSUE TITLE
Spike: Investigate logging of jobs in the airflow operator

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1286]
Airflow allows you to view the logs of a running task inside of your dag.

You can click on the task and it will show the logs on your task.

These logs only include what the airflow operator is logging.  They do not display logs of the actual container job.

This ticket should investigate and see if it is feasible to include logging of the container job into the airflow UI.

Some questions you should answer:

1) Can logging be controlled programmatically?  Can we only log the container if someone asks for the logs?
 a) If logging will happen for every job this could potentially cause a problem.

 2) Can we use binoculars for this logging?

 3) What kind of modifications will need to happen (if any) to our public API in order to support logging?

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-66) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1286?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott
