### ISSUE TITLE
 Update k8s.io/* go modules to latest

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1348]
The k8s.io/ namespaced modules in our go.mod are out of date and should be updated.

This requires more than just a basic upgrade of the packages though. See #1327 for a failed attempt to perform this.

This issue is done when:

* All k8s.io/* go modules are on the latest version that will run in go 1.18
* (bonus points) Document how to do this more easily in the future

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-67) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1348?planning-poker) with ZenHub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by jayofdoom** [comment]
Ensure the new versions upgraded to will be compatible with k8s versions used by G-Research and AWS. This may not be the actual latest version.

*Please* document these versions, and where to find them.
