### ISSUE TITLE
Update documentation to describe what linters/tools are recommended for development for go

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1445]
Currently, we use golangci as our linter.  We should update our documentation to explain how to setup the linter and how to integrate with an editor.

https://golangci-lint.run/ is the linter we use.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-68) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
The documentation should include the following:

1) How to install the linter (linux/mac)
2) Setting up the linter in commonly used editors (VSCode, JetBrains, ...)
3) Process for adding/removing a new linter
    - This process should include an issue to add/remove the linter.
    - PR should fix the linter so it passes in the CI

**Comment by lazyturd** [comment]
Hey, can i be assigned to this? i would like to help

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1445?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott

**Comment by dave-gantenbein** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1445?planning-poker) with Zenhub @suprjinx

**Comment by kannon92** [comment]
@lazyturd Hello!  Our team was discussing issues and there is some internal issues we will have to address.  I suggest taking a different issue if you are still interested in contributing.
