### ISSUE TITLE
Research an Alternative to Alpine for our Base images

### ISSUE THREAD

**Issue by d80tb7** [armadaproject/armada#1500]
Currently we use Alpine as our base images.  Unfortunately, this means that CGO isn't supported which is undesirable.

We should research and (if appropriate) recommend what alternatives are out there, with a view of seeing whether cgo can be supported.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-70) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
Looking online it looks like we can support CGO with alpine.

https://megamorf.gitlab.io/2019/09/08/alpine-go-builds-with-cgo-enabled/

Would this suffice?
