### ISSUE TITLE
Armada OIDC development documentation

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1514]
An Armada developer should be able to quickly and freely configure a test environment for Armada's OIDC authentication support. This can include use of free-as-in-beer services or free-as-in-speech software -- the ability to develop is what matters here.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1514?planning-poker) with Zenhub @ClifHouck @dejanzele @richscott @Sharpz7 @suprjinx
