### ISSUE TITLE
Configure existing armadactl OIDC support

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1515]
armadactl has existing, limited support for OIDC authentication. In this ticket, we should understand this existing support enough to configure it -- even if it's not production-level functional.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1515?planning-poker) with Zenhub @ClifHouck @dejanzele @richscott @Sharpz7 @suprjinx
