### ISSUE TITLE
Ensure armadactl OIDC support caches tokens

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1516]
Once we've explored existing support for armadactl, we should enhance that support to ensure it's production ready.

This may include, but is not limited to:
- Ensuring tokens are cached in a manner normal for a native client application
- Ensuring configuration is sane and understandable for an end-user of Armada.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1516?planning-poker) with Zenhub @ClifHouck @dejanzele @richscott @Sharpz7 @suprjinx
