### ISSUE TITLE
User documentation on how to use armadactl with OIDC

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1518]
We need to ensure our documentation for users of armadactl describe the OIDC support, OIDC modes, and configuration needed to configure OIDC based authentication.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1518?planning-poker) with Zenhub @dejanzele @jayofdoom @kannon92 @richscott @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1518?planning-poker) with Zenhub @ClifHouck @dejanzele @richscott @Sharpz7 @suprjinx
