### ISSUE TITLE
SPIKE: Investigate options for generating example config files

### ISSUE THREAD

**Issue by jayofdoom** [armadaproject/armada#1519]
We need to document possible configuration values for Armada and armadactl; however, it's extremely common for documentation of that nature to get outdated rapidly as the product evolves. Many open source projects solve this by generating configuration documentation manually out of code.

The output of this spike should be issues filed in github laying out the implementation steps and answers to the following questions:
- Should we manually document configs or automatically generate that document?
- What tooling should we use for that documentation?

**Comment by dave-gantenbein** [comment]
@jayofdoom we're iceboxing this pending further detail.

**Comment by jayofdoom** [comment]
Whoops; forgot to fill in a description here -- apologies. Will do that now.
