### ISSUE TITLE
Add unit tests for node affinity in new Armada scheduler

### ISSUE THREAD

**Issue by dejanzele** [armadaproject/armada#1588]
* Investigate and understand logic of the new Armada scheduler
* Add unit tests for node affinity in new scheduler

Approach:

* Branch from [severinson/nodeselection](https://github.com/G-Research/armada/pull/1577)
* Add unit tests for affinity (most of the logic is `internal/scheduler/nodedb.go` and `internal/scheduler/nodedb_test.go`
* Create a PR to merge changes to `severinson/nodeselection` branch

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-72) by [Unito](https://www.unito.io)

**Comment by biswajit-9776** [comment]
Hello, is this issue open for beginners? I have written unit tests for some other files, and I could help add some more to this repository.
