### ISSUE TITLE
Submit a Pull request to add your project as a sandbox project to https://landscape.cncf.io

### ISSUE THREAD

**Issue by dave-gantenbein** [armadaproject/armada#1590]

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1590?planning-poker) with Zenhub @ClifHouck @richscott @suprjinx @dejanzele @Sharpz7

**Comment by kannon92** [comment]
https://github.com/cncf/landscape/pull/2807 is open but there was a request to move our organization.
