### ISSUE TITLE
armadaproject.io: replace existing production install page content with updated content

### ISSUE THREAD

**Issue by dave-gantenbein** [armadaproject/armada#1604]
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-73) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1604?planning-poker) with Zenhub @suprjinx @richscott @Sharpz7 @dejanzele @ClifHouck @headphonejames @kannon92

**Comment by kannon92** [comment]
Our production guide is helm-based.  We walk through our users about what values to use for a production install.  What is your request?

**Comment by Sharpz7** [comment]
I think its making sure it runs and is up to date. Maybe also some methods for actively maintaining it in the future with github actions checks?

**Comment by jimbobby5** [comment]
I would like the guide to be as simple as possible. Currently it references too many pre-reqs (e.g. configuring Redis). I think we already have some kind of umbrella chart that should install everything for you? I also suspect it's very out of date in general.

**Comment by kannon92** [comment]
@jimbobby5 Since GR devs are the only ones that have a production instance, can we maybe consider having GR add this guide?  We don't have anything close to a production instance at GR-OSS.  Is it possible to share the helm charts that GR uses to deploy Armada?
