### ISSUE TITLE
CI: Use docker login in our CI to avoid rate limits

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1619]
We sometimes hit rate limits in our CI pipeline due to docker.  We should add a login step so we can avoid this.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-74) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1619?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx
