### ISSUE TITLE
[Scheduler Ingester] Move Schema To Support Migrations

### ISSUE THREAD

**Issue by d80tb7** [armadaproject/armada#1745]
The current scheduler schema ([clicky](https://github.com/G-Research/armada/blob/master/internal/scheduler/sql/schema.sql)) is currently supplied as a single sql file.  We need to change this so that it uses the migration strategy used by lookout whereby the schema is produced by applying successive migrations.

One challenge here is that Albin's upsert logic ([clicky](https://github.com/G-Research/armada/blob/master/internal/scheduler/dbopswriting.go#L68)) is currently relying on reading a single sql file to determine the schema.  Once we go to a migration based strategy there will be no single file that we can query.  Possible solutions are:

* Read the schema from the db at runtime
* Annotate the structs with the postgres types (my preference)

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-77) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
What about using some existing tooling that supports doing db migrations, such as an ORM? If we don't constrain ourselves to golang for this we open up a lot of lightweight options in Python or Ruby.

**Comment by d80tb7** [comment]
It looks like the standard go tool to do this is https://github.com/golang-migrate/migrate.  I'd be fine with us choosing this- the only tricky bit would be to work out how we could move lookout to use this, as currently it's using its own homebrew migration logic.
