### ISSUE TITLE
[Scheduler] Validate Configuration

### ISSUE THREAD

**Issue by d80tb7** [armadaproject/armada#1747]
For the new scheduler we want to have all configuration validated on application start up.  In order to do this we need a generic way of validating configuration and then, which we can then use to validate the scheduler configuration.  I'm hoping that if we do this well then we can apply the same pattern to all Armada components.

I have done a bit of investigation and I https://github.com/go-playground/validator looks promising, but I'll elave the actual choice of framework up to whoever picks up the ticket.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-79) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Similar to #1746 we should consider non-golang tooling in a dynamic language that would make this easier.
