### ISSUE TITLE
Log Out The Job Request When We Reject It

### ISSUE THREAD

**Issue by d80tb7** [armadaproject/armada#1749]
When Armada rejects a job request, it logs out the rejection message, e.g.

```java
container "x" memory limit (0) below server minimum (1Mi)
```

But it doesn't log out the whole request message. This causes problems because seomtimes users don't know exactly what request they sent us (e.g. the request was generated by some script or by a piece of tooling they don't own).  In this case being able to show them the whole request and why it was invalid would be helpful.

We should therefore log the whole failing request for retrieval later.

Redaction of log fields is **not** required. ~~Note that we should strip out any sensitive information from the request, before logging.~~

We need to be careful about the amount of logging we generate - e.g. if a user submits a batch of 1000 jobs and has a 64 kb jobspec (sadly not impossible)- that will generate 64MB of logs just for that one request. Solutions to that are:

* just log the spec of the first rejected job
* truncate the log output per request to 100K or something
* only log out the specs with different reasons

Chris Martin suggests: a 1k batch of jobs with a 64kb job spec to be the limit of what's reasonable. Get them to test that case (even if they just test it manually- doesn't have to be  test that's run on every build) and see how long it takes (anything more than half a second is an issue)  and how much logging it generates

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-81) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Is there an enum of fields that can't be logged in the code already?

**Comment by richscott** [comment]
**Requirements Update** (per discussion with Chris Martin):

Redaction of log fields is **not** required. 

We need to be careful about the amount of logging we generate - e.g. if a user submits a batch of 1000 jobs and has a 64 kb jobspec (sadly not impossible)- that will generate 64MB of logs just for that one request. Solutions to that are:

- just log the spec of the first rejected job
- truncate the log output per request to 100K or something
- only log out the specs with different reasons

He suggests: a 1k batch of jobs with a 64kb job spec to be the limit of what's reasonable. Get them to test that case (even if they just test it manually- doesn't have to be  test that's run on every build) and see how long it takes (anything more than half a second is an issue)  and how much logging it generates
