### ISSUE TITLE
Add a "Job Story" to developer.md

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#1753]
Add a job story that details each step of a job being run on armada, from client submission to seeing the logs of the pod from lookout.

It would specify:

* What components are used, and at what points through submission
* What communication methods the components are using.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-82) by [Unito](https://www.unito.io)

**Comment by octonawish-akcodes** [comment]
Can I work on this one

**Comment by kannon92** [comment]
I don’t think this is a good ticket for a new contributor. It’s about documenting the architecture which is currently changing.

I appreciate the enthusiasm!

**Comment by Sharpz7** [comment]
Closing due to the rapidly changing nature of the software in its current state.
