### ISSUE TITLE
Add component diagrams to developer.md

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#1754]
Add diagrams showing all the components, and their relationships. This would look similar to a systems engineering Description View

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-83) by [Unito](https://www.unito.io)

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1754?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx
