### ISSUE TITLE
localdev should more clearly show errors in setup

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#1755]
For example, if kind fails to setup ingress, there is no real indication that has happened outside of carefully reading logs.

![](https://files.mcaq.me/4r89b.jpg)

I think we should make it so the setup script stops if an error has been detected, to make it more clear.

**Comment by suprjinx** [comment]
in this case, I do not believe ingress affects most dev/test scenarios -- so do we really want to block for this?

**Comment by kannon92** [comment]
If we want to use localdev plus e2e tests I think we need too.  

The e2e tests I think require the ingress to be working for some of their tests so if it fails to install the tests will fail.

**Comment by Sharpz7** [comment]
Closing due lack of demand
