### ISSUE TITLE
Write a guide for deploying Armada to GKE

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1759]
After https://github.com/dejanzele/armada-infra is moved to our repo, we should write a similar guide for deploying Armada to GKE.

Goals would be a reproducible terraform scripts for creating the GKE cluster and setting up Armada.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-84) by [Unito](https://www.unito.io)

**Comment by sarthaksarthak9** [comment]
kindly, review the pr . Suggest changes if required.

**Comment by sarthaksarthak9** [comment]
@kannon92  done!

**Comment by sarthaksarthak9** [comment]
@kannon92  done!!

**Comment by kannon92** [comment]
> @kannon92 done!!

I don’t see it. You should open a pull request on armada repo so it shows that you want to merge a branch on your fork to our repo.

**Comment by ShivangShandilya** [comment]
hey @kannon92, can you assign me this issue? Would definitely like to work on documentation

**Comment by SD-13** [comment]
Hi @kannon92, Is it still up for grab?

**Comment by AHB102** [comment]
hi @kannon92 , is this issue still open?

**Comment by sarthaksarthak9** [comment]
@AHB102  it is still open!!

**Comment by kannon92** [comment]
Sorry. Yea it is open.

https://github.com/armadaproject/armada/issues/1759 Was started but I’d like to see a demo able instance of armada on GKE before we consider it done.
