### ISSUE TITLE
Write a guide for deploying Armada to AKS

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1760]
We should continue our documentation efforts and have a deployment walk through for setting up Armada on AKS.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-85) by [Unito](https://www.unito.io)

**Comment by sarthaksarthak9** [comment]
@kannon92  , please review the pr . Kindly , suggest the changes if required. Thank you  in advance

**Comment by Sajiyah-Salat** [comment]
hey @sarthaksarthak9 you have'nt open a pr in this project. please open a pr.

**Comment by kannon92** [comment]
https://github.com/armadaproject/armada/pull/2173

**Comment by AHB102** [comment]
Hi @kannon92 is this issue still available ?

**Comment by sarthaksarthak9** [comment]
@AHB102 they are still open!!
