### ISSUE TITLE
Add a guide for deploying Armada to OpenShift

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1780]
Openshift is a popular open source offering of a kubernetes platform.  We should write a guide targeting deployment for Openshift.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-86) by [Unito](https://www.unito.io)

**Comment by octonawish-akcodes** [comment]
I want to work on this

**Comment by kannon92** [comment]
Hey @octonawish-akcodes! We would love to have you help on this.  

We don't have any Openshift clusters so our hope is that someone has an existing one and they could walk through a deployment of Armada on Openshift.  Do you have an existing cluster with Openshift?

If not I believe they have trial options but we have 0 experience on this so we won't be much help on troubleshooting.

**Comment by octonawish-akcodes** [comment]
I will have to look up into this sir, I'll ask if I stuck somewhere thank you :)
