### ISSUE TITLE
armadaproject.io: update developer guide to use localdev/compose

### ISSUE THREAD

**Issue by suprjinx** [armadaproject/armada#1819]

**Comment by behouba** [comment]
Hi, I am Manasse. I am new to `armada` and I would like to contribute to the next GSoC. 
Is this issue related to the usage of the old `docker-compose`  in `localdev/run.sh` and `localdev/stop.sh`? If so, can I open a PR to update these scripts?

**Comment by kannon92** [comment]
Hello @behouba! Thank you for your interest.  I think we are actually considering phasing out the localdev items so this may actually be no longer needed.

**Comment by behouba** [comment]
Ok, thank you @kannon92!
 I'll take a look at other issues)
