### ISSUE TITLE
Tie armada-operator to a specific version of Airflow

### ISSUE THREAD

**Issue by ClifHouck** [armadaproject/armada#1848]
**Is your feature request related to a problem? Please describe.**

Armada-operator should not have conflicting requirements/dependencies with airflow. Tying armada-operator to a specific version (versions?) of airflow should alleviate this problem.

**Describe the solution you'd like**

Guarantee armada-operator has complete compatibility with at least one specific version of Airflow.

**Describe alternatives you've considered**

TBD

**Comment by kannon92** [comment]
From what I understand, this is not actually a good idea.  We had it pinned originally but I was asked to unpin it so they could test upgrades of airflow.  

I was told that building libraries for people to use you really should not pin versions as it makes your library really hard to use.  

@jayofdoom was mostly the person I talked with this about.

**Comment by jayofdoom** [comment]
Sounds like the real solution for this would be some kind of CI, insuring co-installability with recent Airflow.

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1848?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx
