### ISSUE TITLE
Add a rust client

### ISSUE THREAD

**Issue by damelLP** [armadaproject/armada#1863]
I'd like to be able to submit/interact with armada from rust.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-87) by [Unito](https://www.unito.io)

**Comment by Mo-Fatah** [comment]
@damelLP  Is this issue still active ? I see that the PR has been idle for a while, I would like to give a hand if a Rust is still needed

**Comment by damelLP** [comment]
Hey, yes sorry been swamped with day work. Feel free to contribute to it. I was trying to make an example consuming events look ergonomic.
