### ISSUE TITLE
Armada Server CRD and Install Controller

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#1909]
Using the Operator SDK (https://sdk.operatorframework.io/), write a spec (as Go struct definitions) for the run-time configuration of the Armada server, write controller logic to deploy it using Helm, and generate the CRD YAML definition.

Also, the installation controller should run data-model configuration/migration steps:
- set up Pulsar namespaces, partitions, and topics
- (unconfirmed - may need with new Armada scheduler) set up Postgres schema

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1909?planning-poker) with Zenhub @richscott @kannon92 @dejanzele @suprjinx @Sharpz7
