### ISSUE TITLE
Operator: Data-migration for Lookout/Lookout Ingester CRDs

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#1933]
Investigate if the logic in the current Armada repo for the Postgres database that Lookout uses needs to be run during the installation of the Lookout Ingester CRD (and also the Lookout CRD) - if it does, port the logic from the Armada repo to the armada-operator repo such that it's invoked during the installation of the Lookout and/or Lookout Ingester CRDs.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1933?planning-poker) with Zenhub @richscott @kannon92 @dejanzele @suprjinx @Sharpz7

**Comment by richscott** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1933?planning-poker) with Zenhub @ClifHouck
