### ISSUE TITLE
Operator: data-migration logic for armada-server CRD install

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#1934]
Port the logic from the main Armada repo which does the initial data-model migration for the armada-server service, so that installation of the armada-server CRD sets up all the persistent data resources it needs to run.
This includes:
- Redis databases and queues
- Pulsar namespaces, topics, and partitions
- Postgres database schemas (if using the new scheduler that persists to Postgres)

This should result in the armada-server CRD being set up and able to run, without the user having to separately invoke the armada-server with any `--migrate ...` flags, to get it in a runnable configuration.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1934?planning-poker) with Zenhub @richscott @kannon92 @dejanzele @suprjinx @Sharpz7

**Comment by richscott** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1934?planning-poker) with Zenhub @ClifHouck
