### ISSUE TITLE
Lookout V2 CRD and Install Controller

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1941]
Lookout V2 should be installed with our operator.  Similar pattern as lookout.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1941?planning-poker) with Zenhub @richscott @kannon92 @dejanzele @suprjinx @Sharpz7

**Comment by richscott** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/G-Research/armada/1941?planning-poker) with Zenhub @ClifHouck
