### ISSUE TITLE
Switch to native python tooling instead of Makefiles

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#1957]
Use https://github.com/pyinvoke/invoke to manage all python build commands

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-94) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1957?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1957?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
@Sharpz7 is this still valid with our move away from Makefiles?

**Comment by Sharpz7** [comment]
Hmm. Probably no as long as this repo stays as a monorepo.

**Comment by Sharpz7** [comment]
Closing as magefiles will be used.
