### ISSUE TITLE
Add Coverage for UI

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1963]
**Is your feature request related to a problem? Please describe.**
We should also add coverage for our javascript code.

**Describe the solution you'd like**

We should report coverage for the javascript code.

**Describe alternatives you've considered**

**Additional context**

**Comment by kannon92** [comment]
@isaac-jordan or @carlocamurri maybe this would be of interest as you are adding more testing to the UI.

**Comment by isaac-jordan** [comment]
@kannon92 Shouldn't be too difficult as jest supports emitting coverage reports in a few standard formats. Simply changing `"test": "react-scripts test` to `"test": "react-scripts test --coverage` will emit reports in the `coverage/` folder - but currently that will include some auto-generated code in `openapi/`, so requires some fiddling with the `--collectCoverageFrom` arg to exclude that.

**Comment by kannon92** [comment]
Thank you @nand-porko !
