### ISSUE TITLE
Publish the operator image to DockerHub

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#1980]
Once the operator work is complete, we should publish the images and have them ready for release.  

I think we still need to figure out if this will be a Helm cart also.  This ticket is a placeholder once we get further along in our development.

**Comment by dejanzele** [comment]
**Acceptance Criteria**
* Implement GoReleaser for building, packaging & publishing (see implementation in armada)
* Tweak controller-gen to generate resources in a Helm chart

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1980?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx
