### ISSUE TITLE
Spike: investigate using DataDog for CI/CD monitoring

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#1988]
Investigate using DataDog for monitoring of the Armada CI/CD pipeline.  See  https://www.datadoghq.com/product/ci-cd-monitoring/ for more information.

The product brief seems to indicate that a number of the improvement requests in the epic for this ticket might be solved. Most notably, DataDog appears to offer visibility into longitudinal trends of CI/CD processing, which GH Actions plugins don't seem to support.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-97) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
I was also told to look at CodeFresh.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1988?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1988?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx
