### ISSUE TITLE
Install Publish Test Results GH Actions plugin

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#1989]
Install the "GitHub Action to Publish Test Results" plugin into the GH Actions workflow for Armada, for quick badges to indicate test results upon PR merges. See https://github.com/EnricoMi/publish-unit-test-result-action

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-98) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
@nand-porko has asked to take this one.

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1989?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by octonawish-akcodes** [comment]
I want to work on this

**Comment by kannon92** [comment]
Hey @octonawish-akcodes, @nand-porko is actively working on this issue already.

**Comment by nand-porko** [comment]
Hi @richscott and @kannon92 , I have integrated the badge on my [test repo] (https://github.com/nand-porko/github_actions_test). [Here](https://github.com/nand-porko/github_actions_test/actions/runs/4308220429) is an example of what a push looks like, do check the test result posted as comments. Let me know if you wish to add the test report as a comment on PR and/or add a badge to Armada README as well.

**Comment by ashutosh887** [comment]
Hi @nand-porko hope you're able to resolve the issue
Let me know if you need any help

**Comment by SD-13** [comment]
Hey @kannon92 , just wanted to know if this issue is still available or not. If yes, I want to give it a try. Thanks!

**Comment by sarthaksarthak9** [comment]
Is this resolved? If not I would like to work on it!!

**Comment by kannon92** [comment]
@dejanzele pointed out that this is actually in another PR waiting to be merged.
