### ISSUE TITLE
Install Slack Notify Build plugin for GH Actions

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#1991]
Install the Slack Notify Build plugin for Github Actions into the Armada build workflow - see https://github.com/marketplace/actions/slack-notify-build

In consideration of how much Slack traffic/noise this may generate: note that it allows updating of existing Slack messages, as well as being able to specify posting on success, failure, or both.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-99) by [Unito](https://www.unito.io)

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/1991?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by jgiannuzzi** [comment]
Hey team, do you wanna look at how we've done it for ParquetSharp and Consul.NET? We're using https://github.com/pavlovic-ivan/octo-nudge which is much simpler to configure as it doesn't require setting up a bot, but rather just having a Slack webhook URL.
