### ISSUE TITLE
Troubleshoot ingress errors in lookout, etc

### ISSUE THREAD

**Issue by dave-gantenbein** [armadaproject/armada#2082]

**Comment by ClifHouck** [comment]
May have something to do with ingress rules not having hostnames? @dejanzele probably has more constructive context here.

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2082?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx
