### ISSUE TITLE
Create helm/gh pages in new org

### ISSUE THREAD

**Issue by dave-gantenbein** [armadaproject/armada#2083]
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-104) by [Unito](https://www.unito.io)

**Comment by owenthomas17** [comment]
Hi @dave-gantenbein , is there a way that I can somehow do this work? I've just tried to run the local setup script and its failing because it points to a charts repo which doesn't exist (e.g. https://armadaproject.github.io/charts/ doesn't exist)

The circle CI builds do seem to be publishing still to https://github.com/G-Research/charts (e.g. https://github.com/G-Research/charts/tree/circlci-armada_v0.3.49) so I've been able to use those for now. The links are broken in the following places

```bash
docs/local/setup.sh:helm repo add gresearch https://armadaproject.github.io/charts
deployment/armada-bundle/README.md:| https://armadaproject.github.io/charts/ | armada | v0.3.36 |
deployment/armada-bundle/README.md:| https://armadaproject.github.io/charts/ | armada-executor | v0.3.36 |
deployment/armada-bundle/README.md:| https://armadaproject.github.io/charts/ | armada-lookout | v0.3.36 |
deployment/armada-bundle/README.md:| https://armadaproject.github.io/charts/ | armada-lookout-ingester | v0.3.36 |
deployment/armada-bundle/README.md:| https://armadaproject.github.io/charts/ | armada-lookout-migration | v0.3.20 |
deployment/armada-bundle/README.md:| https://armadaproject.github.io/charts | executor-cluster-monitoring | v0.1.9 |
deployment/armada-bundle/Chart.lock:  repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.lock:  repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.lock:  repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.lock:  repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.lock:  repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.lock:  repository: https://armadaproject.github.io/charts
deployment/armada-bundle/Chart.yaml:    repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.yaml:    repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.yaml:    repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.yaml:    repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.yaml:    repository: https://armadaproject.github.io/charts/
deployment/armada-bundle/Chart.yaml:    repository: https://armadaproject.github.io/charts
```

**Comment by kannon92** [comment]
Hey @owenthomas17! Feel free to take this work on!

**Comment by kannon92** [comment]
Create a repo named armadaproject/charts?

**Comment by owenthomas17** [comment]
Yea, that's the one.

**Comment by kannon92** [comment]
https://github.com/armadaproject/charts

Not sure what permissions G-Research/charts had but I think you do what you need to do.

**Comment by owenthomas17** [comment]
Ok great - That's one small step for man. 

As far as I can tell, CircleCI is setup to push to `G-Research/charts` as the user with the following configuration:
`git -c user.name='GR OSS' -c user.email=github@gr-oss.io commit -qam "Pushing new helm charts at version $RELEASE_TAG"`. 

CircleCI also seems to have an ssh-key attributed to this account encapsulated in the environment variable: `$ARMADA_CHART_UPDATE_KEY`.

If the desire is to port new pipelines into github actions, I think the following needs doing by someone with enough permissons as I don't seem to be able to do myself:
- An existing shared services account (or a new one if none exists) needs to be a write collaborator on: https://github.com/armadaproject/charts
- Ideally the branch protection is setup such that:
  - The user from the first step can push straight to master/main with no PR required and push to custom branches with no PR required.
  - No other users/groups/collaborators can push straight to master/main without a PR
- The ssh pub/private key for the user in the first step needs to be added to the github actions secrets for: https://github.com/armadaproject/armada

@kannon92 - Can you let me know when you'll be able to do the steps above?

**Comment by kannon92** [comment]
@richscott may be a better person to shepherd this through.. to be honest I’m not sure we even have those permissions. We will aim to do this but may take us some time.

**Comment by owenthomas17** [comment]
It would be pretty weird if you could create new repo's in an org, but couldn't configure the settings for them. Is that right? 

I'm hoping you guys are able to talk to someone in OSS about the account with the name `GR OSS`. I would of thought that a service account for pipelines would be fairly common in the OSS world. Maybe it wouldn't require an SSH key, but a github token would also work.

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2083?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx
