### ISSUE TITLE
Build interfaces around our postgres access

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2121]
We should make sure that users could bring their own SQL databases into Armada.  Currently we only allow postgres as our db but we should create an interface and potentially allow other databases.

This could help with test improvement as we can add mocks for SQL calls and allow us to run unit tests without an active database.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-110) by [Unito](https://www.unito.io)

**Comment by suryaanshrai** [comment]
Which other databases other than postgres are we expecting Armada to deal with?

**Comment by kannon92** [comment]
At the moment our main user will be using Postgres.  

Generally our goal with this is to allow other relation databases so some that come to mind are MSSQL (Microsoft SQL Server), SQLLite, MySQL and Postgres.  

I don't think we should directly support these in Armada until there is a request to support them.  But what I would like to do is to start changing the code so that we could plug and match other databases.

**Comment by octonawish-akcodes** [comment]
I am interested too in this sir

**Comment by kannon92** [comment]
https://developers.google.com/open-source/gsoc/timeline 

I suggest getting familiar with our project.

I've created some other issues for people to play around with.  We are excited to have this much interest but I ask that you don't take this project unless you are officially allowed to do so via GSOC application.

**Comment by suprjinx** [comment]
I would say abstracting as necessary so that SQLite or Postgres can work interchangeably is a good concrete starting point, as we could then use SQLite for running unit tests instead of requiring Postgres. The existing tests with SQLite db provider would provide an indicator of success.

**Comment by severinson** [comment]
We're using postgres-specific SQL calls for performance (specifically, the postygres-specific copy wire protocol).
In my opinion, adding interfaces around SQL calls would be counter-productive for this reason.
I.e., I don't think we should do it.

**Comment by dave-gantenbein** [comment]
@severinson what's your suggestion for how to solve the underlying issue (we need PG to run unit tests)? I'm pretty sure you expressed an interest in having them run quickly. :)

**Comment by suprjinx** [comment]
I think there are two benefits -- less external dependency for unit tests and more openness in the system which might aid adoption. As long as we keep the postgresy performance stuff in that provider, I don't think it's counter-productive.

**Comment by Chinwendu20** [comment]
Does this mean this is no longer a gsoc project?

**Comment by dave-gantenbein** [comment]
No, this project is still valid, please proceed!

**Comment by octonawish-akcodes** [comment]
Is this project valid then can I proceed to learn more about it?

**Comment by NeerajGartia21** [comment]
Hello @kannon92 @suprjinx ,
I work to work on this project.
Where can I discuss about the same?

**Comment by satyampsoni** [comment]
Is this project going to be a part of LFX summer this year?

**Comment by kannon92** [comment]
> Is this project going to be a part of LFX summer this year?

Yes. https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2023/02-Jun-Aug/project_ideas.md#armada

Applications open up on May 10th.

**Comment by lata-11** [comment]
Hey @kannon92. I want to work on this project under LFX summer mentorship. I am a new contributor to this project. How should I get started? Is there any good-first bug that needs attention, I would be happy to help.

**Comment by i-am-yuvi** [comment]
Hello everyone, I am also interested in this issue and would like to join this as LFX mentorship. Can you help me to get started with this project and issue?

**Comment by satyampsoni** [comment]
Yeah sure @i-am-yuvi. what kind of help do you need?

**Comment by i-am-yuvi** [comment]
Hey @satyampsoni. If you are already working into this issue. Will you mind if you could share some resources to get started with this project.

**Comment by satyampsoni** [comment]
First of all, I would suggest you understand what is Armada and the problem it is trying to solve, You can read the [readme](https://github.com/armadaproject/armada#readme) it explains it well and talks about the resources are mentioned in the readme and I am mentioning some links here too.
1. https://www.youtube.com/watch?v=FT8pXYciD9A
2. https://www.youtube.com/watch?v=B3WPxw3OUl4

I am also looking forward to working on it during LFX and am also researching more about it. I'll be sharing the resources in the Slack channel as I progress with the issue, I just came to know about this issue last day.

Again pls join the Slack channel people there will definitely help you.

**Comment by i-am-yuvi** [comment]
Thanks for this @satyampsoni, I'll definitely join the slack channel

**Comment by akashsawan1** [comment]
Hey, I would love to work on this project. I am familiar with Golang and have a good understanding of MySQL and SQL. I am also highly interested in applying for the LFX mentorship program during the months of June and August.

**Comment by ayush14rastogi** [comment]
I am also interested in this can somebody paste the slack channel link here.

**Comment by Ndohjapan** [comment]
I am interested in this as I have knowledge of Go and SQL databases.

How can I go from here as I would like to join and also apply for the LFX mentorship program

**Comment by suprjinx** [comment]
I think this is the link to our Slack -- https://cloud-native.slack.com/archives/C03T9CBCEMC. If that doesn't work, find #armada channel once signed in.
