### ISSUE TITLE
Improve the reliability of the Armada testsuite in GH Actions

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#2138]
The testsuite in the Armada repo can be flaky, due to random timing errors, asynchronous execution bugs, etc. Review any previous sporadic failures and see if we can improve the overall stability of the testsuite when it's running in GH Actions.

**Comment by kannon92** [comment]
This ticket seems a bit unactionable.  I merged a PR that fixes our Testsuite so not sure if we can close this.

**Comment by kannon92** [comment]
https://github.com/armadaproject/armada/pull/2125 enables our tests to be green again in the CI.
