### ISSUE TITLE
JobService - Allow jobservice to use other SQL databases

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2163]
Our jobservice is used for caching of events for jobs.  We currently use SQLLITE but we have interest in using postgres.  

We should allow our database access to be pluggable.  

We should not break the existing usage of sqllite as that is currently used in production.

Jobservice code in question is here: https://github.com/armadaproject/armada/blob/master/internal/jobservice/repository/sql_job_service.go

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/AR-114) by [Unito](https://www.unito.io)

**Comment by octonawish-akcodes** [comment]
I want to work on this sir

**Comment by ChinmayaSharma-hue** [comment]
As a newcomer to the project, I have reviewed the codebase and noticed that the project currently utilizes a postgres container for internal use. To allow the use of postgres for caching events in the jobservice, I am unsure whether I should create a new postgres container with user-specified information or leverage the existing postgres container and make a new connection. I apologize if my observations are incorrect or incomplete.

**Comment by kannon92** [comment]
@octonawish-akcodes please consider yourself assigned!

@ChinmayaSharma-hue that is a good observation. In production we point to databases servers so the container is mostly for dev purposes

**Comment by Sajiyah-Salat** [comment]
hello @kannon92 I am new to armada project. I need some of your guidance. can you please specify of what would you expect in code. morever can you provide more reosurces to understand this.

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2163?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2163?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by ashutosh887** [comment]
I would like to work on this
/assign

**Comment by michelsumbul** [comment]
Hi guys,
Just to be sure you try with the right version of postresql, we are looking at using the version 15.
Michel
