### ISSUE TITLE
Figure out how to assign GitHub issues to external contributors

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2166]
We should be able to assign issues to other contributors. Hopefully we can do this via GitHub but we may need an action.

**Comment by octonawish-akcodes** [comment]
I can take this, Si as I understood whenever a contributor wants to start working on an issue the contributor can use something like "/assign" keyword to assign himself correct me if I wrong? 

And if its what we wanted I am happy to work on this

**Comment by kannon92** [comment]
Can you do that? I usually assign via UI but I can’t find anyone who isn’t in organization.

**Comment by kannon92** [comment]
Hmm. It seems to work now.
