### ISSUE TITLE
[Community Request] Increase coverage in our repo

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2167]
Unit test coverage provides a way to know how much of your code is covered via tests.

Our overall coverage is around 45% but it should be higher.

For those looking to contribute, this is a good starting point!

I suggest getting PRs small (one file at a time).

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-115) by [Unito](https://www.unito.io)

**Comment by Dinuka-Thathsara** [comment]
Hi.Sir! I'll work on this.

**Comment by kannon92** [comment]
Please just comment on a file you’d like to improve and then work on it!

**Comment by Dinuka-Thathsara** [comment]
sure

**Comment by Chinwendu20** [comment]
Currently working on writing test for internal/scheduler/adapters/adapter.go file

**Comment by Chinwendu20** [comment]
Heyy @akash-kumar-saw, a lot of us are working on this issue, you would just have to pick a file and write a test for it.

**Comment by Chinwendu20** [comment]
I would be wriring a test the internal/lookout/server/lookout.go file
