### ISSUE TITLE
Docs: Reformatting the Readme.md

### ISSUE THREAD

**Issue by octonawish-akcodes** [armadaproject/armada#2168]
I was thinking of Re-formatting the Readme.md file to make it more descriptive and properly aligned.
kannon92 I want to work on this.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-116) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
Can you please explain more what you are planning to do?

**Comment by octonawish-akcodes** [comment]
Like Adding a contributors section that will show kinda like a list of people with their pics who contributed to the Armada repo, Also 
we can add some emoji's if you think its okay not much but wherever necessary and linking to some documentations, contributing guidelines and things like that. Lemme raise a draft PR to show what I mean.

**Comment by satyampsoni** [comment]
GitHub already provides this feature I think. I don't see any value here.

**Comment by Sharpz7** [comment]
Closing: I think our docs are in a better place since this ticket was created.
