### ISSUE TITLE
Update Contributing.md to explain how to get started 

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2182]
Mention both good-first-issues, setting up Armada and mention other projects related in the armadaproject.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-119) by [Unito](https://www.unito.io)

**Comment by octonawish-akcodes** [comment]
Can I work on this one

**Comment by kannon92** [comment]
@octonawish-akcodes thank you for your enthusiasm! I’m going to ask that you focus your efforts on other tickets.

**Comment by Chinwendu20** [comment]
Hello my suggestion is that contributors should be made to run gofmt and make lint after code changes. Perhaps a target should be created for gofmt in the makefile.

**Comment by satyampsoni** [comment]
Is this issue still open?

**Comment by kannon92** [comment]
Yes. I didn’t get a chance to pick this up.

**Comment by Sharpz7** [comment]
Closing - I think any future changes to docs should be more specific and in a separate ticket.
