### ISSUE TITLE
golang-ci module missing in tools.go

### ISSUE THREAD

**Issue by Chinwendu20** [armadaproject/armada#2199]
While running "make lint". I discovered that it needs going-ci, but it is missing in the tools.go file, which should contain all tools needed to run the project

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-120) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
This sounds like a useful fix.  

You could use https://github.com/armadaproject/armada/blob/master/makefile#L593 as a template for this.

**Comment by kannon92** [comment]
I actually don't think it needs to be in tools.go.  That is mostly used as a requirement for building our proto files.  These is a dev tool so I'd prefer a target that downloads this similar to what I shared above.

**Comment by Chinwendu20** [comment]
Thanks in that case my suggestion is that we create a logic that checks if golangci-lint is in the GOPATH, if not the tool is installed. In the same target that runs the lint.

**Comment by Sharpz7** [comment]
I don't think this is needed now. Closing.
