### ISSUE TITLE
Fix caching issue in golangci-lint GitHub action

### ISSUE THREAD

**Issue by dejanzele** [armadaproject/armada#2223]
Without caching enabled in golangci-lint GitHub Actions job, it takes around 5 minutes to lint Golang code.
The golangci-lint action supports caching, but has an intermitent issue mentioned here - https://github.com/golangci/golangci-lint-action/issues/244

Currently caching is disabled in our Lint job with the following lines - https://github.com/armadaproject/armada/blob/master/.github/workflows/go.yml#L32-L33

Either find a way how to run the action with caching enabled deterministically, or create a PR with a fix in https://github.com/golangci/golangci-lint-action

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-122) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2223?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2223?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by Sharpz7** [comment]
Closing - I doubt this is relevant since Dejans changes CI changes
