### ISSUE TITLE
Identify useful linters and rulesets, and fix lint issues

### ISSUE THREAD

**Issue by dejanzele** [armadaproject/armada#2224]
This PR https://github.com/armadaproject/armada/pull/2214 introduces new workflows for Lint and Test.

Currently Linter does following:

* Lint Go using golangci-lint
* Lint Proto using proto-lint
* Lint Docs using markdown-lint
* Lint Helm using helm-check-action
* Lint Docker using hadolint-action

Investigate which linters provide value and investigate which rulesets should be use.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-123) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2224?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2224?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx
