### ISSUE TITLE
Deprecate old workflows after new workflows are merged and tested

### ISSUE THREAD

**Issue by dejanzele** [armadaproject/armada#2225]
This PR introduces new workflows for Lint & Test - https://github.com/armadaproject/armada/pull/2214

After it is merged, the following workflows should be deprecated and removed:

* https://github.com/armadaproject/armada/blob/master/.github/workflows/coverage.yml
* https://github.com/armadaproject/armada/blob/master/.github/workflows/go-integration-free.yml
* https://github.com/armadaproject/armada/blob/master/.github/workflows/go-integration.yml
* https://github.com/armadaproject/armada/blob/master/.github/workflows/go.yml

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-124) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2225?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by Sharpz7** [comment]
This issue can be closed - none of these are in the repo now
