### ISSUE TITLE
Update GitHub actions/steps that use deprecated features

### ISSUE THREAD

**Issue by dejanzele** [armadaproject/armada#2226]
Some actions in this PR https://github.com/armadaproject/armada/pull/2214 use deprecated GH Actions API.

Example - https://github.com/armadaproject/armada/actions/runs/4342671254

![image.png](https://images.zenhubusercontent.com/62d73d0503f0cf046f7e9c70/de73ac9d-cb2c-439c-a0c5-1d555cfbf7ef)

Update versions or submit PR for the affected actions to update them, or implement custom actions.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-125) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2226?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2226?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by kannon92** [comment]
https://github.com/arduino/setup-protoc/issues/59 looks to be almost ready for release but the maintainers are nonrespive.  They even locked the issue because "it got too heated".
