### ISSUE TITLE
Ensure all workflows use Job Summaries for easy job overview

### ISSUE THREAD

**Issue by dejanzele** [armadaproject/armada#2227]
GitHub introduced support for Job Summaries - https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

Example of a summary of the Code Build & Checks workflow - https://github.com/armadaproject/armada/actions/runs/4342671254

Implement Job Summaries for Lint workflow

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-126) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2227?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2227?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by itsaviral2609** [comment]
Hey @richscott, can I work on this issue? Wants to get my hand dirty with github actions if you are busy with some other issues!

**Comment by dejanzele** [comment]
Hello @itsaviral2609,

Thanks for taking interest in improving Armada CI.

I'd ask if you can make the following changes:
* Scenario 1 - lint job succeeds - output a message saying No lint issues in Golang|TypeScript code depending on is it a golang linter job or ts linter job
* Scenario 2 - lint job fails - output a list of lint issues which have the lint error, filename and line number which caused the lint issue

Can you please also create an example PR which introduces a lint issue in either Golang or Typescript to confirm it prints out the lint issues in correct format?

**Comment by itsaviral2609** [comment]
Hi @dejanzele 
Didn't wanted to ask help for this but tried all possible ways to make it print in job summary but its failing after I introduced a error in applications.go file (created a unused function which will be detected by go-lint). 

![Screenshot from 2023-07-29 20-38-08](https://github.com/armadaproject/armada/assets/96782675/d6901fa0-e1f5-4223-ace1-52bffeeaefb5)

![Screenshot from 2023-07-29 20-42-41](https://github.com/armadaproject/armada/assets/96782675/dab67ab6-e169-415d-af58-5307a0700819)

![Screenshot from 2023-07-29 20-43-04](https://github.com/armadaproject/armada/assets/96782675/044c7007-cf68-4b8c-ab09-ecdd60be2756)

A little help in debugging would be appreciated :)
