### ISSUE TITLE
Implement annotations for all linters

### ISSUE THREAD

**Issue by dejanzele** [armadaproject/armada#2228]
GitHub supports Job Annotations where an annotation appears for some line in the code with a comment (used in linting for example) - https://github.blog/2018-12-14-introducing-check-runs-and-annotations/

Lint Go job already does that, implement the same for all other linters in this PR - https://github.com/armadaproject/armada/pull/2214

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-127) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2228?planning-poker) with Zenhub @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2228?planning-poker) with Zenhub @ClifHouck @dejanzele @headphonejames @kannon92 @richscott @Sharpz7 @suprjinx
