### ISSUE TITLE
Operator install manifest

### ISSUE THREAD

**Issue by suprjinx** [armadaproject/armada#2241]
create a manifest in the operator repo that can install the operator via kubectl, so something like this will work: 

`curl github.com/gresearch/armada-operator/config/samples/deploy_operator.yaml | kubectl apply -f -`

this is basically the same as "make install" but it will reference a dockerhub image for the operator and won't require cloning repo, running make commands, etc.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-44) by [Unito](https://www.unito.io)

**Comment by itsaviral2609** [comment]
I feel i can try this issue out! Some additional context required like which apiVersion apps/v1 or any custom-api of armada, ServiceAccount,CustomResourceDefinitions (CRDs) associated with the operator,ClusterRole & ClusterRoleBinding

@suprjinx @Sharpz7

**Comment by Sharpz7** [comment]
Closing, does not belong here and has been addressed.
