### ISSUE TITLE
Reformatting aws-ec2 in docs !!

### ISSUE THREAD

**Issue by ShivangShandilya** [armadaproject/armada#2257]
As I was browsing through docs, I came across aws-ec2, in which all the installation of various dev stack is shown as follows:-
Install docker
Install docker-compose
Install Go
Install Kind
Install kubectl
Install helm

<b>Suggestion to improve the same</b>
What we can do is we can add relevant images and CLI commands to make the documentation even more impressive.
Like for example: In Docker, we can have an image, and for kind,kubectl, and helm we can have CLI commands so that a user can directly copy the very same command which ultimately reduces the hassle of searching it up.

**Comment by kannon92** [comment]
Sounds good! All good additions
