### ISSUE TITLE
Add readme for each armanda component in the cmd folder

### ISSUE THREAD

**Issue by Chinwendu20** [armadaproject/armada#2258]
Trying to understand the codebase as a newbie poses a bit of difficulty especially as some components do not have any documentation in the docs folder. It would really be helpful if there was a readme for each armada component in the cmd directory.

**Comment by ShivangShandilya** [comment]
I think I can add a readme for a few of the components that I have learned about in Armada

**Comment by ShivangShandilya** [comment]
hey @kannon92, I was thinking of adding one for jobservice but correct me if i'm wrong Jobservice allows for creation and submission of jobs right?
