### ISSUE TITLE
[Magefiles] - Support accessing Pulsar, Postgres and Redis from outside the docker network

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2265]
This will be more useful for debugging components locally, and should be supported in our push to have wide coverage of development methods.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-36) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada/2265?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx
