### ISSUE TITLE
[Magefiles] - Remove developer/init.sh and replace with mage targets.

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2278]
`developer/init.sh` effectively does:

- Building the docker images, `go mod tidy` and protoc building
- Building the Lookout UI optionally
- Actually running armada.

This should become 3 mage targets instead, `build`, `ui` and `run`. 

`localdev` would be replaced with `run` and `localdevstop` would be replaced with `teardown`

**Comment by intellect4all** [comment]
Hi @kannon92, what do you think about this? I would love to work on this.
