### ISSUE TITLE
Add support for XCom to Armada operator for airflow

### ISSUE THREAD

**Issue by michelsumbul** [armadaproject/armada#2279]
Hi,

We would to add the support for XCom for the armada operator in airflow.
For information here is a doc on what is XCom: https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/xcoms.html

Here is a doc explaining how the XCom work with the KubernetesPodOperator: https://airflow.apache.org/docs/apache-airflow-providers-cncf-kubernetes/stable/operators.html

Thanks,
Michel

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-34) by [Unito](https://www.unito.io)

**Comment by itsaviral2609** [comment]
Hey @Sharpz7 
I will like to give a shot to solve this issue!
Anything more to keep in mind other than above resources to solve this?

**Comment by dave-gantenbein** [comment]
@itsaviral2609 I think this would be a lot easier to review in the form of a pull request....

**Comment by dave-gantenbein** [comment]
Won't do
