### ISSUE TITLE
JobService needs a lot of memory for concurrent job sets

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2295]
**Describe the bug**

We discovered that when you run 100s of concurrent jobs in a single job set, 2 GB of memory for a job service is not enough.

We can resolve this issue by bumping up the memory limits but we should understand why this is requiring so much memory.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-31) by [Unito](https://www.unito.io)

**Comment by iJanki-gr** [comment]
Actually any amount of memory seems to not be enough. Also with 16GB we eventually reach OOM.
