### ISSUE TITLE
Operator: pause ingesters before migration batch jobs (lookout, scheduler)

### ISSUE THREAD

**Issue by suprjinx** [armadaproject/armada#2339]
Migration batch jobs should pause ingesters before running. If successful, the ingesters should restart with new images, otherwise restart the old/existing image.

This is currently supported for the main lookout service -- the batch job has to succeed before the rest of the reconcile loop runs. We need the main app reconcile loop to pause and potentially halt the ingester reconcile, too.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-6) by [Unito](https://www.unito.io)

**Comment by Sharpz7** [comment]
Does this belong here, or in the operator repo? Since they both pass to Zenhub now

**Comment by dave-gantenbein** [comment]
@Sharpz7 operator repo

**Comment by sbdtu5498** [comment]
Is someone working on this issue currently?

**Comment by Sharpz7** [comment]
Closing. This should not be here.
