### ISSUE TITLE
Operator: helm chart for armada-operator is out of date

### ISSUE THREAD

**Issue by suprjinx** [armadaproject/armada#2340]
the armada-operator chart in /deployment is out of date and needs to be recreated. I think dejanzele had a tool to generate from the kustomize output :question:

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-5) by [Unito](https://www.unito.io)

**Comment by Sharpz7** [comment]
Closing - no longer relavent
