### ISSUE TITLE
Some small but important step towards better contributor experience

### ISSUE THREAD

**Issue by sbdtu5498** [armadaproject/armada#2379]
**Is your feature request related to a problem? Please describe.**

There is no way to recognize which feature has been completed or on which feature someone is currently working, etc.

**Describe the solution you'd like**

Kindly put assignee tags and close the completed features so that it becomes easier for new individuals to get mingled.

**Describe alternatives you've considered**

I think currently there is no automation bot here to manage tasks that can be automated. I would love to see such a bot preferably prow here as it would make things easier for both the maintainers and the contributors alike.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-182) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
Thank you for your suggestion.  I'm not sure how difficult it is to use Prow outside of K8.  

Do you know of any other github action solutions?  We should have an auto close bot and I think generally we need to cleanup issues.

**Comment by sbdtu5498** [comment]
Yes, it can be used. In fact, a lot of CNCF projects use Prow. You just need some infra to spin it up along with some configuration files. For basic prow bot. I can give you a helping hand.

**Comment by shubham-cmyk** [comment]
@sbdtu5498 
I think it's good idea

**Comment by kannon92** [comment]
I think the infra may be an issue at the moment for us.  We would encourage adding a github actions that could close stale issues.

I think generally we try to assign tickets to people as they work on it.

**Comment by sbdtu5498** [comment]
Sure that would be great either. Then adding action for assigning tasks and tracking issues' progress in the sense that whether they are being worked upon or not would be enough for the time being

**Comment by sbdtu5498** [comment]
Also, right now the improvement steps for Armada are being taken by the core team, and thus almost every issue is probably well sought and needs to be resolved. But as soon as the adaptability of the project would increase folks would open some bugs that might be because of some misconfiguration instead. So for that, I think some comment based github action support to add tags such as bugs, etc. by anyone and  triage-accepted and priority-based tags by the maintainers would be a great addition as well.

**Comment by kannon92** [comment]
Agreed!

if anyone wants to play around with startle issues, https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues

**Comment by Sharpz7** [comment]
I am less convinced the repo is active enough that this is needed. Closing for now.
