### ISSUE TITLE
Update system architecture diagram to include all components of the armada bundle

### ISSUE THREAD

**Issue by Chinwendu20** [armadaproject/armada#2448]
Currently, this is how the architecture diagram for armada looks like:

![image](https://github.com/armadaproject/armada/assets/59079323/6a3cd445-6b82-414d-ad19-b84e59afffe1)

As there are still a lot of components in the armada bundle not included in this system architecture, this might not be comprehensive enough and so I suggest we create a new diagram.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-262) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
@Sharpz7 added this diagram a few weeks ago.  Does this answer the questions?

https://github.com/armadaproject/armada/blob/master/docs/design/relationships_diagram.md

**Comment by Chinwendu20** [comment]
Oh wow, it is so nice. Do you think we can copy it to the design website?
https://armadaproject.io/design

**Comment by jayofdoom** [comment]
To be explicit, we render the pages out of the `gh-pages` branch, but we have a github workflow to automatically populate documents from docs/: https://github.com/armadaproject/armada/blob/master/.github/workflows/pages.yml#L27

**Comment by satyampsoni** [comment]
I suggest adding the new diagram to the [system overview](https://github.com/armadaproject/armada/blob/master/docs/design.md). So that people can have a better understanding of how the things are working in the Armada.

**Comment by Sharpz7** [comment]
I think we can close this with https://github.com/armadaproject/armada/pull/2693
