### ISSUE TITLE
Deferrable operator should also have poll_interval

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2473]
We added poll_interval to our armadaOperator.  https://github.com/armadaproject/armada/pull/2444

I noticed that we didn't add this API field to the deferrable operator.  We should add poll_interval as a parameter (https://github.com/armadaproject/armada/blob/master/third_party/airflow/armada/operators/armada_deferrable.py#L83)

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-286) by [Unito](https://www.unito.io)

**Comment by Nawaz027** [comment]
Hey @kannon92 , I am new to this project and would love to take up this issue. Can you please assign it to me?
Thanks in advance.

**Comment by kannon92** [comment]
Assigned!  Thanks for picking it up.

**Comment by sarthaksarthak9** [comment]
May , I also work in this @kannon92 ?

**Comment by sarthaksarthak9** [comment]
May , I also work in this?

**Comment by kannon92** [comment]
@Nawaz027 has already started asked.

**Comment by sarthaksarthak9** [comment]
Need any help @Nawaz027 ?

**Comment by sarthaksarthak9** [comment]
@kannon92  is this issue still up? May I work on this
