### ISSUE TITLE
Resiliency for ArmadaOperator Job Service calls

### ISSUE THREAD

**Issue by iJanki-gr** [armadaproject/armada#2483]
ArmadaOperator depends on jobservice and Armada client instances.

If the jobservice dies the task immediately fails. I think the proper way would be for it to have some backed off retries before giving up.

Same approach is used in many other operators such as KubernetesPodOperator. If an API call to K8s fails the call will be retried a few times "reattaching" to the pod. In particular KPO uses "tenacity" library that could be used here too.

```
@tenacity.retry(stop=tenacity.stop_after_attempt(3), wait=tenacity.wait_exponential(), reraise=True)
     def read_pod(self, pod: V1Pod) -> V1Pod:
         ...
```

I think this is the only way to have resilience for jobservice. Even if we have multiple jobservices using a postgres db, if one replica goes down the connection will be lost and need to be reattempted to connect to the other replica.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-297) by [Unito](https://www.unito.io)

**Comment by iJanki-gr** [comment]
At the moment, if jobservice is down the task will fail. If the jobservice goes down while the task is running it will fail too.

Having multiple replicas in k8s won't help unless there is a retry mechanism built in the operator.
The production scenario would look like multiple replicas and a k8s service. There is no API gateway.

**Comment by pavan12395** [comment]
Hi @kannon92 , I want to take up this issue.

Going through the code of JobService & Armada Operator and above comments , Work involved in this issue could be..

1) Adding back-off retry algorithm in ArmadaClient & JobServiceClient 
2) Adding replicas for JobServiceServer.

It would be helpful for me if anyone can provide feedback on this...
