### ISSUE TITLE
Better Docs on Armada Development for Windows / WSL

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2492]
We have limited information on how to run Armada in these environments. Any documentation additions would be great. Mainly addressing any problems / adding magefile code to fix problems.

There should be limited issues when running `mage localdev minimal testsuite`, but any that appear should be fixed and addressed as the scope of this ticket.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-311) by [Unito](https://www.unito.io)

**Comment by sarthaksarthak9** [comment]
@Sharpz7 I am trying to setup this project in windows via WSL. I set up pre-requisite and get a success for mage localdev minimal testsuite but mage ui is falling

**Comment by Sharpz7** [comment]
Closing - I think this is in a better state now!
