### ISSUE TITLE
Better Docs for running Armada Development on M1/Arm

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2493]
We have limited documentation on this. Any extensions to docs / the magefiles to fix / address issues would be very useful.

There should be limited issues when running `mage localdev minimal testsuite`, but any that appear should be fixed and addressed as the scope of this ticket.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-312) by [Unito](https://www.unito.io)

**Comment by Pradeep-Kurapati** [comment]
Hello,
I would like to solve this issue. I'm completely new to open source. Any guidance you can provide is much appreciated. Thank you.

**Comment by enesonus** [comment]
Hi @Sharpz7 if it is available I can work on this issue,

I went through the [documentation](https://armadaproject.io/contribute) but couldnt find a documentation writing guide. If you could share some insights with me about documentation approach of the project that would be great. 
Thanks.

**Comment by UtkarshUmre** [comment]
I'm new to this project, but I'm interested in working on this good first issue. May I give it a try?

**Comment by richscott** [comment]
Closing this issue, as running/developing Armada on Macbook M1 systems has some functionality bugs beyond documentation, and those are being tracked in https://github.com/armadaproject/armada/issues/2535 -  @UtkarshUmre and others, please follow that ticket instead. I will fill in more current information about the state of running Armada on a Mac M1 in that ticket. Thank you!
