### ISSUE TITLE
Typing `make` does not do anything

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2507]
**Describe the bug**

Type `make` and you get the following error:

```
[ec2-user@ip-172-31-93-184 armada-main]$ make
make: Nothing to be done for `node-setup'.
```
**Expected behavior**
I'd expect some default behavior for make.  Usually `make` runs a build.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-331) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
Turns out `make` will run the first command.  I think we could make this a help command or something more user-friendly.

**Comment by pavan12395** [comment]
Hi @kannon92, I am interested in working on this issue.

Maybe we can output a list of targets and a small description of their action when the user types in make , just like any other help command.
