### ISSUE TITLE
Move localdev/airflow to developer/airflow

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2509]
To line-up with existing changes of moving everything in localdev to developer

Make sure that the github actions workflows have been changed to correctly run upon changes of the files in their new location.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-330) by [Unito](https://www.unito.io)

**Comment by itsaviral2609** [comment]
Hey @Sharpz7 Can I try this issue too?
