### ISSUE TITLE
Change the minimal version for Docker in Mage

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2510]
https://github.com/armadaproject/armada/blob/master/magefiles/main.go#L38

We use mage to state minimum versions for different dependencies. We need to extend the check for Docker to find:

- What is actual minimum version is (Or something acceptable)
- Ensure the user has the docker compose and docker buildx plugins available.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-329) by [Unito](https://www.unito.io)

**Comment by pavan12395** [comment]
Hey @Sharpz7,
I set up Armada in my local system and trying to contribute.
I find this a nice good first issue to solve. Can you assign it to me?

**Comment by sarthaksarthak9** [comment]
@Sharpz7 can I also work on this ?

**Comment by sarthaksarthak9** [comment]
@kannon92 pls assign this issue to me!!

**Comment by kannon92** [comment]
You should be able to assign these things to yourself via top right field called Assignees

**Comment by pavan12395** [comment]
Thanks a lot! , for assigning this Issue to me @kannon92,

I tried using a series of docker-versions on armada starting from docker engine 19.03

I found out Armada works fine with the following versions

docker 20.10.10
docker-compose 1.29.2
docker-buildx 0.6.3

**Comment by Sharpz7** [comment]
Closing as #2534 adds this
