### ISSUE TITLE
Replace Make targets with Mage targets

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2511]
Essentially, we currently have two ways of running commands, `make` and `mage`. This ticket covers two tasks:

- Remove all the commands from `make` that are already covered by `mage`
- Add any missing commands that are not in `mage` into `mage` based on how it is setup in `make`.

Ideally any user that takes this on would write a quick batch script with all the `make` commands, and then slowly build a `mage` equivalent, and make sure they get the same final result.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-328) by [Unito](https://www.unito.io)

**Comment by satyampsoni** [comment]
hey @Sharpz7. Could you pls assign it to me?

**Comment by sambhavgupta0705** [comment]
hey @satyampsoni are you still working on this issue.If not then I would like to try my hands on it .

**Comment by satyampsoni** [comment]
I was out so couldn't work on it. I am working on it now.

**Comment by Sharpz7** [comment]
This ticket does not include https://github.com/armadaproject/armada/issues/2556

**Comment by nitishchauhan0022** [comment]
@satyampsoni are you still woking on this. If not, i can take this up.

**Comment by sambhavgupta0705** [comment]
> hey @satyampsoni are you still working on this issue.If not then I would like to try my hands on it .

@satyampsoni

**Comment by Sharpz7** [comment]
@nitishchauhan0022 if you need any help, feel free to get in touch through the armada community slack in the CNCF workspace :))

https://communityinviter.com/apps/cloud-native/cncf

**Comment by nitishchauhan0022** [comment]
Sure!
