### ISSUE TITLE
Add Python stuff into Localdev

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2556]
This ticket will add a new magefile subcommand:

`mage localdev python`: this will build all the python dependencies.

You will then be able to run everything with:

`mage localdev "full python" airflow start`

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-346) by [Unito](https://www.unito.io)

**Comment by satyampsoni** [comment]
Could you please assign it to me?
