### ISSUE TITLE
deprecated version of actions - python-client, actions.yml(python-tests) workflows

### ISSUE THREAD

**Issue by ShivangShandilya** [armadaproject/armada#2594]
**Describe the bug**

`actions/checkout@v2`, `actions/setup-python@v2` and `arduino/setup-protoc@v1` actions have been deprecated.

**Files Or Markdown that can reproduce the issue**

![image](https://github.com/armadaproject/armada/assets/101946115/973ee3cf-d6c6-4821-bb94-655b0c2041bd)

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-383) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
Maybe a duplicate. https://github.com/armadaproject/armada/issues/2226

Just for awareness.
