### ISSUE TITLE
Lookout Handover

### ISSUE THREAD

**Issue by carlocamurri** [armadaproject/armada#2684]
# Handover

## Adding "active job sets" to browser state for custom views and as URL parameter

Recent PR has added the "active job sets" toggle to only include jobs that are in "active" job sets in the table.
This means that jobs will only display if they belong to a job set with at least 1 job in Queued, Leased, Pending or Running state.

Currently, this field isn't being stored in the application state, and as such is not surfaced to the user in either the URL parameters or the localstorage state (so it can't be used for custom views either, as they are stored in localstorage). 

### Update `JobTablePreferencesService`
1. Update the `JobTablePreferences` object to include a field for `activeJobSets` (probably nullable): https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/services/lookoutV2/JobsTablePreferencesService.ts#L19-L48
1. Add URL param for `activeJobSets` with a short name (e.g. `active`): https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/services/lookoutV2/JobsTablePreferencesService.ts#L63-L81
1. Add logic for `activeJobSets` to convert from `JobTablePreferences` to URL Params: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/services/lookoutV2/JobsTablePreferencesService.ts#L83
2. Add logic for `activeJobSets` to convert from URL params to `JobTablePreferences`: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/services/lookoutV2/JobsTablePreferencesService.ts#L122
3. Add override for `activeJobSets` when merging localstorage prefs and URL params: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/services/lookoutV2/JobsTablePreferencesService.ts#L172-L178

### Update `JobsTableContainer`
1. Change the default value of `activeJobSets` to that given by `initialPrefs` (like here: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/services/lookoutV2/JobsTablePreferencesService.ts#L172-L178): https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/containers/lookoutV2/JobsTableContainer.tsx#L186
2. Update conversion logic to `JobTablePreferences` to include `activeJobSets`: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/containers/lookoutV2/JobsTableContainer.tsx#L238
3. Update logic to set the React state from the `JobTablePreferences`: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/containers/lookoutV2/JobsTableContainer.tsx#L269-L296
4. Include `activeJobSets` as a dependency of the relevant effect: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/containers/lookoutV2/JobsTableContainer.tsx#L299

Note that this doesn't include other changes that should be made to the relevant test files, though getting them to compile and adding a test in `JobTablePreferencesService` would be good.
Worth verifying that nothing breaks if existing configurations exist with an empty `activeJobSets` field.

## Removing Lookout v1

We eventually want to remove Lookout v1.
There are a few things that need to be done in order to migrate fully.

### Migrating Lookout v1 UI
The source code of Lookout is in `armada/internal/lookout/ui/src`.
Here is a general list of directories/files that should be kept, under `src`:
* All non-directory files in the root of `src`
* `/utils/`
* `/services/lookoutV2/`
* `/models/`
* `/hooks/`
* `/containers/lookoutV2/`
* `/components/lookoutV2/`

There are also some changes that need to be made in order for it to work:
* The `NavBar` can be changed to remove all V1 components (or removed entirely): https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/App.tsx#L98
* Some utilities will remain unused and could be removed (e.g. https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/utils.tsx#L226)
* Change the `App` props to only include V2 specific components: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/App.tsx#L64-L79
* Remove V1 specific config options from fetching logic: https://github.com/armadaproject/armada/blob/master/internal/lookout/ui/src/utils.tsx#L30-L45

### Migrating Lookout v1 API
The Lookout V1 API is the only API that serves the UI as well as the configuration.
Before removing it, the following things need to be done:
* The config endpoint needs to be added to the V2 API: https://github.com/armadaproject/armada/blob/master/cmd/lookout/main.go#L105-L108
* The UI static files need to be served: https://github.com/armadaproject/armada/blob/master/cmd/lookout/main.go#L110-L111
* If Lookout V1 is still to be maintained, CORS config will have to be added to allow the UI served from the V2 API to access the V1 API
* The Lookout V2 API Dockerfile needs to include the built UI: https://github.com/armadaproject/armada/blob/master/build/lookout/Dockerfile#L8
* Ingresses need to be updated for the same CNAMEs to continue working

### Migrating the Lookout v1 Ingester
This component should be able to be removed along with the database.

To migrate, if we want to continue supporting V1:
* Serve the UI and config in Lookout V2 API
* Change ingress to point to CNAME
* When ready, remove UI components
* Remove Lookout V1 API and ingester

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-469) by [Unito](https://www.unito.io)

**Comment by zuqq** [comment]
As of #3067, version 1 of Lookout is almost entirely gone (apart from `/job-sets`; see #3052).
