### ISSUE TITLE
Doc: In documentation section System overview link is broken

### ISSUE THREAD

**Issue by Parthiba-Hazra** [armadaproject/armada#2691]
In the Documentation section of README.md file the **System overview**([System overview](https://github.com/armadaproject/armada/blob/master/docs/design/README.md)) link is broken.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-476) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
Thank you for that! Are you interesting in fixing that?
