### ISSUE TITLE
Add a virtual-kubelet provider for Armada

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2702]
**Is your feature request related to a problem? Please describe.**

(Virtual Kubelet)[https://github.com/virtual-kubelet/virtual-kubelet] is a way to bring a Kubernetes front end and allow for your execution environment to be something other than Kubernetes.  

A goal of this feature is to enable a provider for virtual-kubelet that will allow one to submit pods directly to Armada.  

Virtual-Kubelet provides a list of [providers](https://virtual-kubelet.io/docs/providers/).  

This ticket is reserved for a LFX Mentee so we will be applying for a fellow to work on this in Fall 2023.  

The fellow would need to learn some about the design of virtual-kubelet, research how other providers work, and then build a provider for Armada.  Ideally, if the provider is fully functional, we can ask virtual-kubelet to add this as an example provider on their website.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-488) by [Unito](https://www.unito.io)

**Comment by shivaabhishek07** [comment]
Hey there, I am interested in this project and will apply for this project when Mentee applications are open.
What I have understood by reading the above description is that we need to create a virtual-kubelet for Armada(implementing it by knowing design of virtual-kubelet and researching on how other providers are being worked).

For contributing and knowing about Armada, Are there any beginner friendly issues to solve?

**Comment by punithnayak** [comment]
Hey looks interesting project .Will definitely apply when forms come up

**Comment by Lan-ce-lot** [comment]
Hey, I am learning virtual-kubelet recently, I am very interested and happy to apply for this project.😃

**Comment by sivasathyaseeelan** [comment]
Hi there, I am very interested and definitely apply for this project!!

**Comment by anj20** [comment]
Hi, I have worked with virtual-kubelet previously. I am interested in this.

**Comment by sarthaksarthak9** [comment]
@kannon92  is application for this LFX fall project closed?

**Comment by Sharpz7** [comment]
We are no longer running are LFX Mentorship for the upcoming session, but that might change overtime.

If anyone has experience with virtual kubelet, let me know and we can work on this issue together.

**Comment by punithnayak** [comment]
Hey @sharpz7 I would love to work with you and will definitely apply I am not well versed but have a good history of open source
contributed to Wikimedia Foundation (as a gsoc inter and currently contributing to chromium )

**Comment by Sharpz7** [comment]
Hey @punithnayak I think for this specific PR, we really need someone that has used virtual kubelets. Feel free to check out some other tickets though :))

**Comment by deepakdinesh1123** [comment]
Hello @kannon92  @Sharpz7  I've been working on virtual kubelets and have formulated an initial design. I'd be eager to hear your thoughts and engage in a discussion if you're interested.

**Comment by kannon92** [comment]
Hey @deepakdinesh1123, maybe this would be a good agenda item for the community meeting. @Sharpz7?

A design doc would be useful.

**Comment by deepakdinesh1123** [comment]
@kannon92 I am working on a design doc, I will share it with you as soon as its done.

**Comment by deepakdinesh1123** [comment]
@kannon92 @Sharpz7 Sorry for the delay, I was caught up in some other work the entire week, I have created a initial version of the design doc here [virtual kubelet design doc](https://docs.google.com/document/d/1s5uvBScXJmjTJfi4OoRaziczfxx6o4gdNXSeZCmuviI/edit?usp=sharing) please let me know the changes that I have to make.

**Comment by deepakdinesh1123** [comment]
@kannon92 Did you get a chance to look at my proposal? Can you please point out the mistakes in my proposal so that I can rectify them?

**Comment by kannon92** [comment]
I think the proposal is good.  I would prefer a bit more details on the implementation of the provider.  I think you may run into issues like we did with the airflow operator so I'd suggest thinking about how the jobservice can help you here.  

But I would also like @Sharpz7 to weigh in as he is more involved with Armada than I am.

**Comment by deepakdinesh1123** [comment]
@kannon92 It has been a week without any response, can you please let me know if I can contact anyone else regarding this issue?

**Comment by kannon92** [comment]
You could post on the armada slack channel.

**Comment by stackedsax** [comment]
Thanks, @kannon92 for continuing to post to this thread.  You probably have some other duties to attend to over at RH these days, so we'll find another human to go through the proposal.

@richscott, @dave-gantenbein, @Sharpz7 have you looked at this recently?

**Comment by richscott** [comment]
@deepakdinesh1123 I think the proposal looks good. Using Hashicorp Nomad as a possible first kubelet provider would work nicely, as you can run that locally without needing to provision third-party cloud provider resources.

**Comment by richscott** [comment]
Closing this issue - the project has decided not to pursue this as a priority issue. However, @deepakdinesh1123 , if you would like to still work on this as a project, we'd always welcome any pull requests.
