### ISSUE TITLE
Make the UI responsible

### ISSUE THREAD

**Issue by punithnayak** [armadaproject/armada#2731]
**Is your feature request related to a problem? Please describe.**
Yes
The UI  

**Describe the solution you'd like**
Make the Mobile view responsive

**Describe alternatives you've considered**

**Additional context**
I see the current version, not responsive 
https://ui.demo.armadaproject.io/
![image](https://github.com/armadaproject/armada/assets/110713318/fc86dfe7-ed99-496c-b647-0c4b2f8f6345)

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-517) by [Unito](https://www.unito.io)

**Comment by punithnayak** [comment]
Hey ,@kannon92 is this relevant issue if yes can you assign me to work on it

**Comment by dave-gantenbein** [comment]
I don't think this is a valid use case - nobody is doing batch ML processing from their mobile phone.
