### ISSUE TITLE
Broken navigation links : Missing Annotations in Markdown Files

### ISSUE THREAD

**Issue by YashPimple** [armadaproject/armada#2732]
**Describe the bug**
Was going through the quickstart guide and currently, the website [quickstart section](https://armadaproject.io/quickstart) contains links through Markdown files, but some of these links are not working as expected. Upon investigation, it has been identified that the links are not properly annotated in the quickstart markdown file, leading to broken navigation and functionality on the website.

**Files Or Markdown that can reproduce the issue**
Changes need to be made in [quickstart.md](https://github.com/armadaproject/armada/blob/gh-pages/quickstart.md) file

**Expected behavior**

All links in the Markdown files should function correctly and navigate users to the intended destinations.

**Actual behavior**

Plain text is visible on the [website](https://armadaproject.io/quickstart) 
<img width="1029" alt="issue-1" src="https://github.com/armadaproject/armada/assets/97302447/90bb698f-ac61-45f8-9dc0-e537b533d98b">

**Additional context**

I would like to work on it 

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-518) by [Unito](https://www.unito.io)

**Comment by kannon92** [comment]
Thanks for pointing that out.  Please feel free to open an issue.  We have some docs on how to build/test the website.

**Comment by YashPimple** [comment]
Hello @kannon92,

I have a question regarding the mentioned issue. The issue pertains to the "Quickstart" page on the [website](https://armadaproject.io/quickstart). According to the [contribution guide](https://armadaproject.io/contribute), changes related to the website should be made on the `gh-pages` branch. I would like to confirm whether I should solely focus on updating `gh-page`s branch **or** should I make corresponding updates to the main branch to maintain on-point information across both branches.

**Comment by Sharpz7** [comment]
@Mo-Fatah is this issue good to close?

**Comment by Sharpz7** [comment]
Closing for now.
