### ISSUE TITLE
Armada V1 and Armada V2 diagrams

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2738]
Armada is migrating to a new set of components. To help users with that move, we need to have diagrams of both setups.

Currently we have https://github.com/armadaproject/armada/blob/master/docs/design/diagrams/relationships/armada_system.png, which is **created using code** from here https://github.com/armadaproject/armada/blob/master/docs/design/diagrams/relationships/generate.py. The one change that needs to happen, is it should be called "Lookout V2" instead of just "Lookout".

For the Lookout V1 Doc, it should instead look like this: https://drive.google.com/uc?id=1XtXdCP2dVXa2pXqLFGHdeSNkh8A6hBt8. Where items crossed out are part of V2, and the items in the green box are all one component.

We should have https://github.com/armadaproject/armada/blob/master/docs/design/relationships_diagram.md be changed to include both diagrams. I expect a PR for this to be a back-and-forth process.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-524) by [Unito](https://www.unito.io)

**Comment by Pradeep-Kurapati** [comment]
@Sharpz7 would you like both diagrams in a single generate.py file or seperate python programs?

**Comment by Pradeep-Kurapati** [comment]
When I run generate.py file, it is not able to access images. I changed the reference to "images/armada.png" from "../files/armada.png" but still it's not accessing images. I don't know if it unique to my environment or is it something I don't understand. Please help me.

P.S: I changed "Lookout" to "Lookout V2". 

![armada_systems_diagram](https://github.com/armadaproject/armada/assets/113408145/1aef7f46-c3d2-4c94-ac29-ea550d769b4a)

**Comment by Pradeep-Kurapati** [comment]
After hours of exploration, I finally found solution.
In `with Diagram()`, I commented out `filename` parameter and it is working!
But the produced image will be in **relationships** folder and not in **out** folder. 
Need help here.

![image](https://github.com/armadaproject/armada/assets/113408145/e55f5c4b-6245-4a48-90fb-52f327549ad8)

should we add this info in our [README.md](https://github.com/armadaproject/armada/tree/master/docs/design/diagrams/relationships#readme) ?

**Comment by Pradeep-Kurapati** [comment]
Please review Armada V2 diagram

![image](https://github.com/armadaproject/armada/assets/113408145/d9cf59b8-3965-4ea1-a7bc-f761575006f1)

**Comment by Sharpz7** [comment]
Good spot with the I/o issues, feel free to edit it and document it as you see fit to get it working.
