### ISSUE TITLE
[Mage] Improve localdev error messages

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2768]
In cases where invalid args are given, we should give good error messages instead of memory errors.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-554) by [Unito](https://www.unito.io)

**Comment by octonawish-akcodes** [comment]
@kannon92 Can I work on this?

**Comment by kannon92** [comment]
With https://github.com/armadaproject/armada/pull/2799 merged, we can close.  Thank you to @nitishchauhan0022 for working on this!
