### ISSUE TITLE
ArmadaErrors unit test is flaky

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada#2863]
https://github.com/armadaproject/armada/pull/2817

If you pull that branch, you can replicate those unit test failures.  These should be fixed before the upgrade to GRPC to 1.57.

**Comment by YashPimple** [comment]
Heyy @kannon92 I would like to work on this issue

**Comment by kannon92** [comment]
So I found some more info on this:

https://github.com/armadaproject/armada/pull/2817

if you pull that branch you’ll get test failures. Feel free to take the change.

**Comment by Mo-Fatah** [comment]
Hi @YashPimple :wave: Any updates on this ? We can help you if you are stuck.

**Comment by sarthaksarthak9** [comment]
> Heyy @kannon92 I would like to work on this issue

any updates?

**Comment by Sharpz7** [comment]
@sarthaksarthak9 feel free to take it

**Comment by YashPimple** [comment]
> Hi @YashPimple :wave: Any updates on this ? We can help you if you are stuck.

Hello @Mo-Fatah I am making progress on the issue and will soom draft a PR on it 👍🏻
Thanks for checking in
