### ISSUE TITLE
Remove Makefile from repo

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#2899]
We should be in a position now to just use magefiles / mage.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-684) by [Unito](https://www.unito.io)

**Comment by diva-21** [comment]
Hey @Sharpz7 , if i remove makefile, then it wouldnt cause any disturabances/errors to other dependencies?

**Comment by Mo-Fatah** [comment]
@diva-21  Our scripts are now fully managed by [mage](https://magefile.org/), the `makefile` file is no longer maintained. Feel free to open a PR removing it and we will merge once it is possible. I can assign this issue to you if you wish

**Comment by diva-21** [comment]
Okay then ,I will remove and keep pr.Assign it to me @Mo-Fatah .

**Comment by diva-21** [comment]
Kept pr @Mo-Fatah ,need review on it.

**Comment by sarthaksarthak9** [comment]
@Sharpz7 is this issue still up?
