### ISSUE TITLE
feat: add DCO check in Armada's PRs

### ISSUE THREAD

**Issue by ShivangShandilya** [armadaproject/armada#2916]
This feature can only be added by the maintainers and  I think this a feature we should adopt.
To enable DCO checks:

1. Search up DCO and select Install ( mine says configure cause I have already installed it in my repos )
![Screenshot from 2023-08-24 23-32-29](https://github.com/armadaproject/armada/assets/101946115/31779613-c17b-4d87-ad7d-5146f3d464ae)

2. Select the org where we want to make this change ( in our case Armada )
![Screenshot from 2023-08-24 23-33-46](https://github.com/armadaproject/armada/assets/101946115/a7b8cfee-5945-4f49-a082-9862eecbdc95)

Should work like a charm

**Comment by Sharpz7** [comment]
@dave-gantenbein What do we think?

**Comment by dave-gantenbein** [comment]
Yes, we need DCO per CNCF guidelines. I'm surprised they haven't flagged this already.

**Comment by Sharpz7** [comment]
I submitted a request to the armadaproject admin. Hopefully that works

**Comment by Sharpz7** [comment]
Closing. We now have DCO
