### ISSUE TITLE
Add note about signed commits to Contributor documentation

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#2958]
The Armada repo now uses the DCO plug-in in its Pull Request checks, and requires that all future commits have a "Signed-Off" attribute in every commit in PRs - see https://github.com/apps/dco .

A prominent note should be added to the `CONTRIBUTING.md` doc (and perhaps elsewhere in `docs/` and `developer/` that informs potential contributors that they will need to use the `--signoff` option to `git commit` (maybe add a link to the Git docs for commit) for all commits in their Pull Request branch. It will be much easier for them to do this up-front, rather than have to fix/amend their commits later, due to PR check failures.

**Comment by kannon92** [comment]
One thing I noticed is that the app isn’t required as I’ve seen a lot of PRs merge without enforcing the check.
