### ISSUE TITLE
Fail-fast in Test workflow

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#3102]
In `.github/workflows/test.yml`, since the `go-mod-up-to-date` job will run separately/concurrently with the `go-unit-tests` and `go-integration-tests` jobs, if there is an error in the go-mod-up-to-date job, it's probably not worthwhile to run the other two. We could speed up the failure case scenario by adding a `needs: go-mod-up-to-date` clause to the latter two jobs, this would speed up overall workflow processing when there's a module issue - see https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow for more info.

**Comment by jaydee029** [comment]
Hi, I would like to work on this.
