### ISSUE TITLE
Merge CI Issues and tickets Together

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#3172]
These issues should be merged

https://github.com/armadaproject/armada/issues/3074
https://github.com/G-Research/gr-oss/issues/468
https://github.com/armadaproject/armada/issues/2987

**Comment by richscott** [comment]
The latter two issues are now merged into the first (#3074 which is an epic) - I have created several new individual tickets comprising the action items in https://github.com/G-Research/gr-oss/issues/468 and #2987 has been added as a task in the #3074 epic.
