### ISSUE TITLE
CI: implement `check-required` action in same fashion as FastTrackML

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#3189]
See https://github.com/G-Research/fasttrackml/blob/main/.github/workflows/check-required.yml

**Comment by kanha-gupta** [comment]
does it require code changes too or just yamls ?

**Comment by richscott** [comment]
I believe it's mostly just the Github Actions workflow YAML file changes as they are doing in the FasttrackML project - see
  https://github.com/G-Research/fasttrackml/blob/main/.github/workflows/check-required.yml
although there is a small amount of NodeJS (Javascript) logic in that YAML file there.

**Comment by pavlovic-ivan** [comment]
There will be small changes to yaml files. We want to extract this action entirely, and put it in a common place/repo, so it can be reused

**Comment by pavlovic-ivan** [comment]
Relates to: https://github.com/armadaproject/armada/issues/3235
