### ISSUE TITLE
CI: Rework/Optimize download target

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#3190]
Inspect and dissect the download target as it looks like the most complicated target  and most time-consuming target to the workflows.
- [x] outcome: expected to get dirs that can be cached (like those for tools) and cache those only, conditionally
- [x] download target should be removed at the end and use bootstrap tools instead
- [x] cache tools from tools.yml
- [x] tools conditionally used/required/installed

**Comment by pavlovic-ivan** [comment]
Hi @richscott, these 2 PRs cover the tasks in this issue:

- https://github.com/armadaproject/armada/pull/3181
- https://github.com/armadaproject/armada/pull/3229

do you agree with closing this issue as done?

**Comment by richscott** [comment]
@pavlovic-ivan I agree - now closing this issue as done.

**Comment by pavlovic-ivan** [comment]
Thanks!
