### ISSUE TITLE
Switch to k3s or k3d

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada#3196]
Kind does not run without privileged docker, which means that internal GR folks cannot use localdev.

I instead suggest switching to either https://[k3d](https://k3d.io/v5.6.0/).io/v5.6.0/ or https://github.com/k3s-io/k3s. 

Using k3s to force us to generate the manifests / helm charts to setup anyways. I think that's an acceptable barrier to put up, and brings the dev setup closer to the prod setup, but we would have to figure out how to get the binaries into a k3s pod as you build them (a single pod with a volume?)

k3d would be easier to setup but wouldn't move us closer to a prod dev setup.

**Comment by Sharpz7** [comment]
Let me know your preference for k3d or k3s. I would vote for k3s

**Comment by kannon92** [comment]
Kind has a rootless option: https://kind.sigs.k8s.io/docs/user/rootless/

**Comment by severinson** [comment]
Let's not do this work without putting some thought into it first. Kind does have a rootless mode but there were issues getting it to work at GR, tho this may not be an insurmountable problem.

**Comment by dave-gantenbein** [comment]
@severinson - can you share details on the GR issues, and is it something we can help with? The diverse ways in which people set up development environments is a constant source of friction.
