### ISSUE TITLE
CI: PRs with auto-merge turned on still get merged when CI checks are failing

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#3235]
It appears that when a Pull Request has *auto-merge* enabled, PRs are still merged after approval by Armada maintainers *and* when CI checks are failing.  This has been observed before (up to several months ago, from what other devs have observed), but most recently happened on Monday, Jan 8 2024.

The PR that was auto-merged, despite having failing checks is https://github.com/armadaproject/armada/pull/3217

The action check that failed is https://github.com/armadaproject/armada/actions/runs/7451299198

The PR to revert that broken change (so as to get `master` healthy again) was  https://github.com/armadaproject/armada/pull/3231 . The Action run for that PR is at https://github.com/armadaproject/armada/actions/runs/7451476802 

Some investigation and/or testing to see how the workflow(s) cause auto-merge to be executed, even if CI checks fail, should be done, and fixed, if possible.

**Comment by pavlovic-ivan** [comment]
Relates to: https://github.com/armadaproject/armada/issues/3189

**Comment by pavlovic-ivan** [comment]
I think this one can be closed. Do you agree @richscott ?

**Comment by richscott** [comment]
@pavlovic-ivan Yes, I agree - closing now.
