### ISSUE TITLE
CI: automate publishing of new `armadactl` releases to Krew plug-in index

### ISSUE THREAD

**Issue by richscott** [armadaproject/armada#3382]
Now that `armadactl` has been added to the Krew plug-in index (see https://github.com/kubernetes-sigs/krew-index/pull/3280 and https://krew.sigs.k8s.io/plugins/), we should automate the publishing of new `armadactl` releases to that index. 

See documentation on automating this publishing process using Github Actions at
https://krew.sigs.k8s.io/docs/developer-guide/release/automating-updates/

**Comment by vishalvivekm** [comment]
@richscott Can you please assign this issue to me, I'd like to work on it.

**Comment by richscott** [comment]
Hi, @vishalvivekm - unfortunately, our team has decided not to pursue this ticket at this time. If you'd still like to help out on the Armada project, we'd love any help on improving the unit-test coverage in some parts of the repository - an issue to track that is at 
https://github.com/armadaproject/armada/issues/3390 - another developer - @Bharadwajshivam28 - has been working on some changes for that, but as it's a large ticket, feel free to find a code function listed in the ticket and add some new tests for it. Thanks!

**Comment by dave-gantenbein** [comment]
Won't do
