### ISSUE TITLE
Job Service subscription manager logic does not handle errors on job event message stream correctly

### ISSUE THREAD

**Issue by Sovietaced** [armadaproject/armada#3553]
If the [job service subscription manager goroutine](https://github.com/armadaproject/armada/blob/master/internal/jobservice/eventstojobs/manage_subs.go#L271-L338) encounters a server error (besides an EOF) from the Armada API it will be stuck in a terminal state reading the same error from the stream and writing it to the database, endlessly.  That is because a stream error is terminal. The server ends the stream with an error and any calls to read from the stream will return the same error over and over again. This is a common mistake with gRPC stream client logic unfortunately.

See: https://groups.google.com/g/grpc-io/c/XcN4hA9HonI

> Client-side, io.EOF is returned directly from grpc-go steram.Send() calls when the server closes the stream.  At that point, Recv() should be called until it returns a non-nil error to receive the server's messages and eventually the status.  If io.EOF is returned by Recv(), that indicates a success; otherwise that is the final status of the RPC.  All errors are permanent from the standpoint of that stream -- subsequent streams are possible using the same client, even if it is a connection error, as the client automatically attempts to reconnect.  Make sure you always call Recv() on the stream until you get a non-nil error or cancel the context used when creating the stream, or else a goroutine and other resources will be leaked.

**Files Or Markdown that can reproduce the issue**

This diff will update the mock server to behave like a real gRPC server, which returns the terminal error over and over again.
https://github.com/armadaproject/armada/commit/a385e07e6a8c1471a3dfc77e1bbe04a7d4f9b3c5

Making this change will fail the existing unit tests.

**Expected behavior**

The expected behavior is that the job service will be robust to errors returned by the Armada API server and will eventually converge instead of getting stuck in a terminal state. 

**Actual behavior**

The Job Service will cache the last error received on the stream into the DB and continue to write the error into the DB endlessly, until the service is rebooted. 

**Additional context**

I have a prospective fix which simply returns from the goroutine when a stream error occurs, however the subscription timeout is currently set to 300 seconds by default which feels like a poor user experience. I am happy to provide a PR

**Comment by dave-gantenbein** [comment]
Hi @Sovietaced! We'd be happy to look at the PR, but FYI we're in the process of phasing out the job service in favor of an API endpoint that returns the same info. This will simplify things overall from a deployment perspective, but if it unblocks you today send it along and we'll take a look. Thanks!

**Comment by Sovietaced** [comment]
> Hi @Sovietaced! We'd be happy to look at the PR, but FYI we're in the process of phasing out the job service in favor of an API endpoint that returns the same info. This will simplify things overall from a deployment perspective, but if it unblocks you today send it along and we'll take a look. Thanks!

I would prefer not to maintain a fork at work so here ya go: https://github.com/armadaproject/armada/pull/3555
