### ISSUE TITLE
Problems with Armada getting started experience

### ISSUE THREAD

**Issue by csantanapr** [armadaproject/armada#3575]
I did a livestream today in CNCF channel to show Armada, without trying it before to evaluate first time user experience.
You can watch from here https://youtu.be/N-lqmr0zfNk?t=1752

TLDR; I was not able to install armada on local kind cluster

- Website no documentation how to run in kind as quickstart
- Running https://github.com/armadaproject/armada/blob/master/docs/local/setup.sh
Failed with
  ```
  + helm install lookout-migration gresearch/armada-lookout-migration --version v0.3.20 --wait -f docs/quickstart/helm/values-lookout.yaml
  Error: INSTALLATION FAILED: open docs/quickstart/helm/values-lookout.yaml: no such file or directory
  ```
- I tried mage but it doesn't work on mac https://github.com/armadaproject/armada/issues/2535
- I tried devcontainer and it didn't work in devpod or local docker desktop devContainer from VSCode https://github.com/armadaproject/armada-operator/tree/main/dev/runbooks
- Using operator https://github.com/armadaproject/armada-operator/tree/main/dev/runbooks didn't work problem with rbac-proxy image wrong tag in helm, and armadactl didn't create queue
- Ran docker-compose up using https://github.com/armadaproject/armada/blob/master/docker-compose.yaml   is not documented had problems, and no documentation on how to connect and configure the [context](https://github.com/armadaproject/armada/blob/master/docs/demo.md#armadactl-configuration) in armadactl

**Comment by dejanzele** [comment]
Hi @csantanapr,

Thanks for raising this issue.

We already discussed and we will reiterate on our docs and get back to you.

**Comment by csantanapr** [comment]
@dejanzele any progress on this? I'm doing another CNCF livestream on Jun 20th 3PM EST

**Comment by dejanzele** [comment]
Hi @csantanapr 

We have merged following PRs which should improve the installation experience:
* website - https://github.com/armadaproject/armada/pull/3719
* operator - https://github.com/armadaproject/armada-operator/pull/305
* armada - https://github.com/armadaproject/armada/pull/3670

The new Quickstart is tested on OSX and Ubuntu.

I'll close the PR as completed.

Thank you for all the suggestions!
