### ISSUE TITLE
Quickstart download old verision of armadactl

### ISSUE THREAD

**Issue by csantanapr** [armadaproject/armada#3674]
**Describe the bug**
Quickstart download old verision of armadactl

In the script https://github.com/armadaproject/armada/blob/master/docs/local/armadactl.sh#L20 
Downloading version 0.3.6 latest is 0.8.2

**Comment by dejanzele** [comment]
Hi,

Thanks for raising this issue!

This has been fixed in https://github.com/armadaproject/armada/pull/3670.

I will close this issue as completed.
