### ISSUE TITLE
Old chat versions in quickstart

### ISSUE THREAD

**Issue by csantanapr** [armadaproject/armada#3676]
**Describe the bug**

As a new user doing the quickstart I would like to try the latest version of the project.
Looking at the script https://github.com/armadaproject/armada/blob/master/docs/local/setup.sh#L3-L10
The versions are very old
```ini
KIND_IMG="kindest/node:v1.21.10"
CHART_VERSION_ARMADA="v0.3.20"
CHART_VERSION_ARMADA_EXECUTOR_MONITORING="v0.1.9"
CHART_VERSION_KUBE_PROMETHEUS_STACK="13.0.0"
CHART_VERSION_NATS="0.13.0"
CHART_VERSION_POSTGRES="12.4.2"
CHART_VERSION_PULSAR="2.9.4"
CHART_VERSION_REDIS="4.22.3"
```
**Expected behavior**
At least I would like to see ARMADA and ARMADA_EXECUTOR_MONITORING to use latest version 0.8.2

I was not able to find a e2e tests that execute this quickstart flow in a github action

**Comment by dejanzele** [comment]
Hi,

Thanks for raising this!

We have deprecated this examples in https://github.com/armadaproject/armada/pull/3670 and now the official installation guide is https://github.com/armadaproject/armada-operator?tab=readme-ov-file#quickstart

I will close this as completed.
