### ISSUE TITLE
C# client does not handle jobsets with "/" in their name

### ISSUE THREAD

**Issue by JamesMurkin** [armadaproject/armada#369]
**Expectation**
Armadactl and C# client would behave the same

**Problem**
If you have a jobset called "//some/job/set/name" and attempt to watch it, you'll find:

`armadactl watch queue //some/job/set/name`

Works fine

Whereas if you do the same with the C# client, you get:

`Status: 404
Response: 
Not Found`

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-129) by [Unito](https://www.unito.io)

**Comment by Sharpz7** [comment]
Closing as no longer needed.
