### ISSUE TITLE
Production deployment docs issues

### ISSUE THREAD

**Issue by dvianello** [armadaproject/armada#415]
Trying to follow https://github.com/G-Research/armada/blob/master/docs/production-install.md to deploy Armada on an EKS cluster, I bumped in a few issues:

- [x] `values.serviceAccount` creation should only be used in the creation of ServiceAccounts for Armanda and Armada-Executor if it's non-null, otherwise creation fails
- [ ] Default value for armada-executor defined [here](https://github.com/G-Research/armada/blob/a12eab832a7001e2545c96094d7cc4cd3870e3a3/deployment/executor/values.yaml#L3) points to a non-existing tag. 
- [ ] Default `nodeselector` for `armada-executor` doesn't work for EKS deployments, since control plane nodes are _not visible_ to the end-user. `nodeSelector: null` fixes it, but it might be worth calling it out explicitly in the docs? 
- [x] Updating `applicationConfig` for `armada-executor` only updates the Secret but doesn't force the pod to roll. Can this be forced in some way with helm? 

HTH!
Dario

**Comment by JamesMurkin** [comment]
Hey:

1. Genuine bug, we'll fix
2. This was done for when publishing the chart, we can try think of a nicer way to do this.
3. This is documented [here](https://github.com/G-Research/armada/blob/f6cb498f5dc9230cd4bed71b9967b98bdec1fe0f/docs/helm/executor.md#executor-node-configuration). I can make this clearer in the production install docs
4. This can be fixed and probably just a good idea in general.

**Comment by dvianello** [comment]
Hi, 

2) is it possible to change the CI build to push a `latest` tag on master builds? That way you can default to `latest` in the charts and leave to the users to pin a version if they need to? Seems to be quite common as an approach.

3)yes, might be worth linking that specific readme from the production install docs. I didn't really notice that existed until after I worked it out myself thanks to Google :-) 

One more thing: `cert-manager` has changed the annotation to be used on Ingresses from `certmanager.k8s.io/cluster-issuer` to `cert-manager.io/cluster-issuer`, so you might want to update that as well.

**Comment by jankaspar** [comment]
The plan is to publish versioned charts in https://github.com/G-Research/charts and have people install things from there. The automation for that is almost in place, just few things to fix. The whole cloning of the repository is not nice anyway. I don't want to encourage people to use master builds as they are not that stable. If we do `latest` tag it should be latest release.

**Comment by dvianello** [comment]
> I don't want to encourage people to use master builds as they are not that stable. If we do `latest` tag it should be latest release.

Ah, yes, very true. Update `latest` on tag builds, as you suggested, would indeed be the best of the two worlds!
