### ISSUE TITLE
Website image needed

### ISSUE THREAD

**Issue by c-rindi** [armadaproject/armada#496]
We need to copy the docs/quickstart/grafana-screenshot.png file to _pages/quickstart/grafana-screenshot.png so that https://armadaproject.io/quickstart/grafana-screenshot.png works.
We should just need to update the “Copy site files” step in the GH Actions workflow that copies the files to the gh-pages branch.
ericjohnsohnisc

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-131) by [Unito](https://www.unito.io)

**Comment by ericjohnsohnisc** [comment]
Submitted a PR to fix this!

**Comment by punithnayak** [comment]
Hey @c-rindi @ericjohnsohnisc  if this task is still pending and no action is taken can I create a PR for this?

**Comment by Sharpz7** [comment]
I don't think this is something we need right now. Could be part of a larger ticket in the future to try and make what armada is doing more visible to new users.
