### ISSUE TITLE
How can I submit tf-job in armada?

### ISSUE THREAD

**Issue by denkensk** [armadaproject/armada#536]
After I test the example in https://github.com/G-Research/armada/blob/master/example/jobs.yaml 

Is there any methods  to submit tf job? The object `job` isn't used frequently.  The job of Tensorflow or Pytorch is widely used. https://github.com/kubeflow/tf-operator/blob/master/examples/v1/dist-mnist/tf_job_mnist.yaml

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-133) by [Unito](https://www.unito.io)

**Comment by jankaspar** [comment]
Hi, Armada currently does not support TF Jobs, the closest to it you can get is job with multiple podSpecs, its possible to submit jobs like this:

```
queue: test
jobSetId: job-set-1
jobs:
  - priority: 0
    podSpecs:
      - containers:
          ...
        resources:
          ...
      - containers:
          ...
        resources:
          ...
```
Armada will aim to schedule multiple pods in one of the clusters at the same time.

Adding support of custom jobs specifications like TF Jobs and other kubeflow types (https://www.kubeflow.org/docs/components/training/) is something we have considered, but have not implemented yet. 

Are you planning to use Armada for specific use case?

**Comment by denkensk** [comment]
> Hi, Armada currently does not support TF Jobs, the closest to it you can get is job with multiple podSpecs, its possible to submit jobs like this:

But if I set the  tf job with multiple podSpecs, How can tf-operator operate it?


> Are you planning to use Armada for specific use case?

Yes, But our job is mainly AI/BigData like tfjob\Pytorch\spark


> Armada will aim to schedule multiple pods in one of the clusters at the same time.
Adding support of custom jobs specifications like TF Jobs and other kubeflow types (https://www.kubeflow.org/docs/components/training/) is something we have considered, but have not implemented yet.

I'm looking forward to this feature. Do you have a general schedule？

**Comment by denkensk** [comment]
@jankaspar  Thanks

**Comment by jankaspar** [comment]
Hi, sorry for late reply,
We don't have any schedule for the support of additional job types. But we would be happy to accept any PRs.

You are right, its not possible to use Tensor Flow operator, but you can use Tensor Flow in the multi node jobs without the operator.

**Comment by richscott** [comment]
Closing this ticket, due to age and this feature still not being planned. Please reopen if this is still strong interest in this feature.
