### ISSUE TITLE
Add instructions in the quickstart document for remote setup on gh-pages

### ISSUE THREAD

**Issue by dans77777** [armadaproject/armada#911]
instead of setting up armada locally , we can run armada on remote EC2 instance which will be more flexible and reliable . I would like to add steps for this in quickstart document.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/BATCH-140) by [Unito](https://www.unito.io)

**Comment by dejanzele** [comment]
@dans77777 would an Armada Bundle helm chart be a better option?
There are ways to run on an EC2 instance, and we already have a script which can be reused, but in my opinion, deploying Armada in k8s cluster seems more native and intuitive.

Here is a PR which adds the Armada Bundle helm chart - https://github.com/G-Research/armada/pull/962
